#!/usr/bin/env python3
"""Enrich remaining 45 visa pages (J-Z) with 5 sections each."""
import os, re

BASE = r"C:\Users\chemi\Documents\evisa\pacific-main\www\en"

# Country-specific data for all 45 remaining pages
DATA = {
"japan": {"visas":[("Tourist (Short-term Stay)","90 days","Free (68 countries)","Visa-free for 68 countries; others need embassy visa"),("Work Visa","1-5 years","JPY 3,000-6,000","Certificate of Eligibility (COE) from employer/sponsor"),("Student Visa","Duration of studies","JPY 3,000","CoE, acceptance letter, financial proof JPY 2M+"),("Highly Skilled Professional (HSP)","5 years","JPY 6,000","Points-based (70+ points), fast-track to PR"),("Specified Skilled Worker (SSW)","1-5 years","JPY 6,000","Skills exam, 14 designated industries"),("Spouse/Family Visa","1-3 years","JPY 6,000","Marriage certificate, sponsor income proof"),("Business Manager","1-5 years","JPY 6,000","JPY 5M+ capital, business plan, office in Japan"),("Working Holiday","1 year","Free-JPY 3,000","Age 18-30, bilateral agreement countries"),("Transit","72 hours","Free","Shore pass for transit passengers"),("Digital Nomad","6 months","JPY 3,000","Annual income JPY 10M+ ($68k), health insurance")],"proc":[("Tourist","1-5 business days","Free","N/A","N/A"),("Work (COE)","1-3 months","JPY 3,000-6,000","N/A","N/A"),("Student","2-3 months","JPY 3,000","N/A","N/A"),("HSP","10 business days","JPY 6,000","N/A","N/A")],"health":"No mandatory vaccinations for Japan. No health exam required for short stays. Work/student visa holders staying 3+ months must enroll in National Health Insurance (NHI) - covers 70% of medical costs, ~JPY 20,000/month. COVID-19 vaccination not required. No quarantine requirements. Japan has excellent healthcare standards. Police clearance required for work visas. Biometric data (fingerprints, photo) collected at immigration for all foreigners 16+.","extension":"Tourist visa holders cannot extend their 90-day visa-free stay in most cases - must leave Japan. Some nationalities can get 90-day extension at immigration office (JPY 4,000). Work/student visa renewal at immigration 3 months before expiry. Overstay penalties: immediate detention, deportation, 5-year re-entry ban (1 year if voluntary departure). Multiple overstays result in 10-year ban. Working on tourist visa is illegal - penalties include detention and deportation.","refusal":"Common refusal reasons: insufficient financial proof, unclear travel purpose, previous immigration violations, incomplete documents. No formal appeal process for visa refusals. Applicants can reapply with additional documentation. Embassy decisions are final. Engaging an immigration lawyer (gyosei shoshi) recommended for complex cases. Student visa refusals can be reconsidered with updated COE."},
"jordan": {"visas":[("Tourist Visa on Arrival","30 days","JOD 40 (~$56)","Available at Queen Alia Airport for most nationalities"),("Jordan Pass","30 days","JOD 70-80 (~$99-113)","Includes visa fee + Petra + 40 attractions. Min 3 nights stay."),("e-Visa","30 days","JOD 40","Available for 150+ nationalities online"),("Business Visa","30 days","JOD 40","Invitation letter from Jordanian company"),("Work Visa","1 year","JOD 300-500","Employer sponsorship, labor permit"),("Student Visa","Duration of studies","JOD 40","Acceptance from Jordanian university"),("Transit Visa","48 hours","JOD 10","For transit passengers")],"proc":[("VOA","Instant","JOD 40","N/A","N/A"),("Jordan Pass","Instant (online)","JOD 70-80","N/A","N/A"),("e-Visa","3-7 days","JOD 40","N/A","N/A"),("Work","2-4 weeks","JOD 300-500","N/A","N/A")],"health":"No mandatory vaccinations. Yellow Fever certificate required if arriving from endemic area. No health exam required for tourists. Health insurance recommended. COVID-19 vaccination not required. Jordan has good private healthcare in Amman. Police clearance may be required for work permits.","extension":"Tourist visa can be extended at nearest police station for additional 2 months (free if done before expiry). Must register at police station within 14 days if staying in private accommodation. Overstay fine: JOD 1.5/day. Significant overstays may result in detention and deportation. Jordan Pass users must stay minimum 3 consecutive nights to qualify for free visa.","refusal":"Refusals uncommon for tourist visas. May occur due to nationality restrictions (Israeli stamps may cause issues), insufficient funds, or security concerns. No formal appeal process. Can reapply after addressing issues."},
"kuwait": {"visas":[("Tourist e-Visa","90 days","KWD 3 (~$10)","Online for 53 eligible nationalities"),("Visit Visa (sponsor)","3 months","KWD 5-10","Must be sponsored by Kuwait resident"),("Business Visa","1 month","KWD 3","Company sponsor in Kuwait required"),("Work Visa (Residency)","2 years","KWD 10-50","Employer sponsorship, medical clearance"),("Family Visit","3 months","KWD 3-5","Sponsored by resident family member"),("Transit Visa","72 hours","Free","Airline transit passengers")],"proc":[("e-Visa","2-3 days","KWD 3","N/A","N/A"),("Visit","1-2 weeks","KWD 5-10","N/A","N/A"),("Work","2-6 weeks","KWD 10-50","Express: 1-2 weeks","KWD 50-100")],"health":"Medical exam mandatory for work/residency visa: HIV, Hepatitis B/C, TB, blood tests. Must be done at approved clinics. Health insurance provided by employer for workers. No vaccination requirements for tourists. COVID-19 vaccination not required.","extension":"Tourist visa can be extended once for 90 days at General Department of Residency. Work visa renewal through employer. Overstay fine: KWD 2/day ($6.50). Overstayers may be detained, deported, and face re-entry ban. Must have valid residency to remain in Kuwait.","refusal":"Refusals common for single women under 40 traveling alone (escort requirement). Security screening delays for certain nationalities. No formal appeal. Reapplication possible through sponsor."},
"laos": {"visas":[("Visa on Arrival","30 days","$30-42","Available at international airports and border crossings"),("e-Visa","30 days","$50 + $5 service fee","Online application for 60+ nationalities"),("Tourist Visa (Embassy)","60 days","$40","Applied at Lao embassy/consulate"),("Business Visa (B2)","30 days","$50-70","Business invitation letter"),("Transit Visa","7 days","$20","For transit through Laos")],"proc":[("VOA","15-30 minutes","$30-42","N/A","N/A"),("e-Visa","3-5 days","$55","N/A","N/A"),("Embassy","3-5 days","$40","Express: 1-2 days","$60")],"health":"No mandatory vaccinations but Yellow Fever certificate required if coming from endemic area. Hepatitis A/B, Typhoid, Japanese Encephalitis recommended. Malaria prophylaxis recommended for rural areas. No health insurance requirement but strongly recommended. Medical facilities very limited outside Vientiane - medical evacuation to Thailand standard practice.","extension":"30-day visa extendable at immigration office in Vientiane for $2/day (max 60 additional days). Overstay fine: $10/day. Significant overstays may result in detention. Immigration office: Vientiane, near Morning Market. Processing: 1-3 days for extension.","refusal":"Refusals rare for tourist VOA. May occur for certain nationalities. No formal appeal. Re-entry possible after resolving issues."},
"liechtenstein": {"visas":[("Schengen Short Stay","90 days in 180","Free (visa-exempt) or EUR 80","Same as Schengen visa - entry via Switzerland/Austria"),("Schengen Visa C","90 days","EUR 80","Apply at Swiss embassy (handles Liechtenstein visas)"),("Residence Permit","1 year+","CHF 200+","Very restrictive - limited quotas"),("Work Permit","1 year","CHF 200+","Employer sponsorship, extremely competitive")],"proc":[("Schengen C","10-15 days","EUR 80","Express: 5 days","EUR 80"),("Residence","3-6 months","CHF 200+","N/A","N/A")],"health":"Same as Schengen requirements. Travel health insurance minimum EUR 30,000 coverage mandatory. No specific vaccination requirements. EU/EEA EHIC card accepted for emergency care.","extension":"Schengen 90/180 day rule applies. Cannot extend beyond 90 days without residence permit. Overstay: Schengen-wide ban possible. Extremely difficult to obtain long-term residence - population controlled.","refusal":"Same as Schengen refusal procedures. Apply through Swiss embassy. Appeal through Swiss administrative courts."},
"luxembourg": {"visas":[("Schengen Short Stay","90 days in 180","Free (visa-exempt) or EUR 80","Standard Schengen rules"),("Schengen Visa C","90 days","EUR 80","Apply at Luxembourg embassy/VFS"),("National Visa D","1 year+","EUR 50","Work, study, family reunion"),("Work Permit","1 year","EUR 50","ADEM labor market test, employer sponsorship"),("Student Visa","Duration of studies","EUR 50","University acceptance, EUR 14,000/year funds")],"proc":[("Schengen C","15 days","EUR 80","Express: 5 days","EUR 80"),("National D","1-3 months","EUR 50","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000 minimum. No mandatory vaccinations. Luxembourg has excellent public healthcare (CNS system). Residents must join CNS. EHIC for EU citizens.","extension":"Schengen 90/180 rule. National visa holders register at commune within 3 days. Overstay penalties: fine, deportation, Schengen-wide ban up to 5 years.","refusal":"Standard Schengen refusal procedures. Appeal to Tribunal Administratif within 3 months. High acceptance rate for Luxembourg."},
"macau": {"visas":[("Visa-Free Entry","30-90 days","Free","Duration depends on nationality (30-90 days)"),("Visa on Arrival","30 days","MOP 100 (~$12)","For nationalities not eligible for visa-free"),("Work Visa (Blue Card)","6 months-2 years","MOP 500-1000","Employer sponsorship, DSAL approval"),("Student Visa","Duration of studies","MOP 200","University acceptance letter"),("Family Reunion","1 year","MOP 200","Macau resident sponsor")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("VOA","15-30 minutes","MOP 100","N/A","N/A"),("Work","1-3 months","MOP 500-1000","N/A","N/A")],"health":"No mandatory vaccinations. No health exam for tourists. Work permit requires medical exam. Macau has good public healthcare at Centro Hospitalar Conde de Sao Januario. Health insurance recommended.","extension":"Visa-free stays generally not extendable. Must exit and re-enter. Work visa renewal through employer 30 days before expiry. Overstay fine: MOP 500/day.","refusal":"Rare for tourists. Work visa depends on labor market test. No formal appeal for tourist entry refusal."},
"malaysia": {"visas":[("Visa-Free Entry","90 days","Free","160+ nationalities (30-90 days depending on country)"),("eVISA","30 days","MYR 120-460","For nationalities requiring visa (China, India, etc.)"),("eNTRI","15 days","MYR 20","China and India nationals only, single entry"),("Social Visit Pass","90 days","Varies","Tourism, family visit"),("Employment Pass (EP)","2-5 years","MYR 120-1000","Employer sponsorship, minimum salary MYR 3,000"),("MM2H (My Second Home)","5-10 years","MYR 500-5000","Age 35+, financial requirements, fixed deposit"),("Student Pass","Duration","MYR 120-500","EMGS approval, university acceptance"),("Malaysia Digital (DE Rantau)","1-2 years","MYR 1,000","Digital nomad, MYR 24,000/year income"),("Transit","120 hours","Free","TWOV for many nationalities")],"proc":[("eVISA","3-5 days","MYR 120-460","N/A","N/A"),("eNTRI","24-48 hours","MYR 20","N/A","N/A"),("EP","1-3 months","MYR 120-1000","N/A","N/A"),("MM2H","3-6 months","MYR 500-5000","N/A","N/A")],"health":"No mandatory vaccinations for most travelers. Yellow Fever certificate required if arriving from endemic area. Medical exam required for Employment Pass and MM2H: chest X-ray, blood tests (HIV, Hepatitis B, VDRL). Foreign workers must register with FOMEMA. MDAC (Malaysia Digital Arrival Card) mandatory for all arrivals - free online form.","extension":"Social Visit Pass 90-day stay generally not extendable for visa-exempt nationals. Employment Pass renewal through employer 3 months before expiry. MM2H renewable. Overstay: compound fine MYR 500+, detention at immigration depot, whipping (caning) possible for illegal workers, 5-year entry ban. Malaysia takes overstay very seriously.","refusal":"Common reasons: suspicious travel patterns, inadequate funds, previous immigration violations, blacklisted. No formal appeal for entry refusal. eVISA rejections can be contested through VLN Global. Reapplication possible after 3 months."},
"maldives": {"visas":[("Visa on Arrival (Tourist)","30 days","Free","All nationalities - free visa on arrival at Male airport"),("Business Visa","30 days","Free on arrival","Business invitation letter"),("Work Visa","1 year","MVR 2,000-5,000","Employer sponsorship, quota approval"),("Student Visa","Duration","MVR 1,000","University acceptance"),("Dependent Visa","1 year","MVR 2,000","Sponsored by work visa holder")],"proc":[("Tourist VOA","Instant","Free","N/A","N/A"),("Work Visa","2-4 weeks","MVR 2,000-5,000","N/A","N/A")],"health":"No mandatory vaccinations except Yellow Fever if arriving from endemic country. IMUGA (Traveller Declaration) mandatory - free online form, submit 96 hours before arrival. No health exam for tourists. Health insurance recommended - limited medical facilities outside Male. Medical evacuation to Sri Lanka/India for serious cases.","extension":"Tourist visa extendable at immigration for additional 60 days (max 90 total). MVR 750 fee. Overstay fine: $10/day. Must depart within visa validity. Resort stays arranged by hotel.","refusal":"Very rare for tourists as visa is free on arrival. May be refused for: no return ticket, no hotel reservation, insufficient funds, blacklisted. No appeal."},
"mexico": {"visas":[("Visa-Free Entry","180 days","Free","65+ nationalities (USA, EU, UK, Canada, Japan, etc.)"),("Tourist Card (FMM)","180 days","Free (air) / ~$30 (land)","Included in airfare; land border requires fee"),("Temporary Resident","1-4 years","$50 application + $5,000-8,000 card","Income $2,500+/month OR $42,000 savings"),("Permanent Resident","Indefinite","$50 + $6,000-8,000","After 4 years temporary OR marriage to Mexican"),("Work Visa","1-4 years","$50 + $4,000-8,000","Employer sponsorship through INM"),("Student Visa","1 year (renewable)","$50 + $3,000-5,000","University acceptance, financial proof"),("Digital Nomad","1-4 years","Same as Temp Resident","Remote work for foreign company, income proof"),("Business Visitor","180 days","Free (visa-exempt)","Meetings only - cannot receive Mexican salary")],"proc":[("Visa-free/FMM","Instant","Free","N/A","N/A"),("Temp Resident","2-4 weeks","$50 + card fee","N/A","N/A"),("Permanent","3-6 months","$50 + card fee","N/A","N/A")],"health":"No mandatory vaccinations. No health exam required. Mexico has good private healthcare (Angeles, Medica Sur, ABC Hospital). IMSS voluntary insurance for residents $500-5000 MXN/year. No COVID-19 requirements. Travel health insurance recommended.","extension":"FMM 180 days cannot be extended - must exit Mexico. Temporary Resident renewable annually at INM office for up to 4 years total. Overstay: fine ~$350, possible entry ban. Overstay >60 days may require leaving Mexico and reapplying.","refusal":"Common at land borders due to 'voluntario' status. Border agents can deny entry or limit stay. Common reasons: suspected working without permit, frequent entries/exits (permanent tourist), insufficient funds. Embassy visa refusals can be reconsidered with additional documentation."},
"moldova": {"visas":[("Visa-Free Entry","90 days in 180","Free","EU, USA, Canada, UK, most developed countries"),("Visa on Arrival","90 days","EUR 40","Available for some nationalities at Chisinau airport"),("e-Visa","90 days","EUR 40","Online application for eligible nationalities"),("Work Permit","1 year","MDL 1,350","Employer sponsorship"),("Student Visa","Duration","MDL 680","University acceptance")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("e-Visa","5-7 days","EUR 40","N/A","N/A"),("Work","2-4 weeks","MDL 1,350","N/A","N/A")],"health":"No mandatory vaccinations. No health exam for tourists. Medical facilities adequate in Chisinau, limited elsewhere. Health insurance recommended.","extension":"90-day visa-free stay not extendable without residence permit. Work permit holders register at BMA. Overstay: fine, deportation, entry ban up to 5 years.","refusal":"Rare for visa-exempt nationals. Standard rejection for incomplete documents. No formal appeal. Can reapply."},
"myanmar": {"visas":[("e-Visa (Tourist)","28 days","$50","Single entry, arrive at Yangon/Mandalay/Nay Pyi Taw airports"),("e-Visa (Business)","70 days","$70","Business invitation, single entry"),("Visa on Arrival","30 days","$50","Very limited nationalities (Japan, South Korea)"),("Embassy Visa","28-70 days","$40-70","Applied at Myanmar embassy/consulate"),("Social Visit","28 days","$40","Visit family/friends"),("Meditation Visa","70 days","$50","Registered meditation center invitation")],"proc":[("e-Visa","3-5 days","$50","Express: 1 day","$80"),("Embassy","3-5 days","$40-70","Express: 1-2 days","$56-100")],"health":"No mandatory vaccinations but Yellow Fever certificate required from endemic areas. Hepatitis A/B, Typhoid, Japanese Encephalitis recommended. Malaria prophylaxis for rural areas. Medical facilities very limited - evacuation to Bangkok for serious cases. Travel/medical evacuation insurance essential.","extension":"Tourist e-Visa not extendable. Must leave within 28 days. Business visa extendable at immigration in Yangon. Overstay: $3/day fine, detention possible. Must pay fine before departure.","refusal":"Political situation may affect visa issuance. Refusals based on nationality restrictions, previous violations. No formal appeal. Check current Myanmar travel advisories before applying."},
"nepal": {"visas":[("Visa on Arrival","15-90 days","$30-125","Available at Tribhuvan Airport and land borders"),("Tourist Visa 15 days","15 days","$30","Multiple entry"),("Tourist Visa 30 days","30 days","$50","Multiple entry"),("Tourist Visa 90 days","90 days","$125","Multiple entry"),("Trekking Permit (TIMS)","Per trek","$20-50","Required for most trekking routes"),("Work Visa","1 year","$100-300","Employer sponsorship, Department of Labor"),("Student Visa","Duration","$50-100","University acceptance")],"proc":[("VOA","15-45 minutes","$30-125","N/A","N/A"),("Work","2-4 weeks","$100-300","N/A","N/A")],"health":"No mandatory vaccinations but Yellow Fever certificate if from endemic area. Altitude sickness medication recommended for trekking above 3000m. Hepatitis A/B, Typhoid recommended. Medical facilities very limited outside Kathmandu. Evacuation insurance essential for trekkers. Nepal Mountaineering Association requires medical certificate for climbing permits.","extension":"Tourist visa extendable at Department of Immigration in Kathmandu or Pokhara. $3/day. Maximum 150 days per calendar year. Overstay: $5/day fine. Significant overstay may result in future visa refusal.","refusal":"Very rare - Nepal has open visa policy. May occur for citizens of Nigeria, Ghana, Zimbabwe, Swaziland, Cameroon, Somalia, Ethiopia, Iraq, Palestine, Afghanistan (require pre-approval). Can apply through embassy."},
"netherlands": {"visas":[("Schengen Short Stay","90 days in 180","Free or EUR 80","Visa-exempt for 60+ nationalities; others need Schengen C"),("Schengen Visa C","90 days","EUR 80","Standard Schengen tourist/business visa"),("MVV (Authorization Temp Stay)","90 days to pick up)","EUR 210","Required before applying for residence permit"),("Work Permit (TWV/GVVA)","Max 3 years","EUR 320-1,050","Employer sponsors, salary threshold EUR 3,549+/month"),("Orientation Year (Zoekjaar)","1 year","EUR 210","For recent graduates of Dutch or top-200 universities"),("Student Visa","Duration","EUR 210","University acceptance, EUR 13,000/year funds"),("Highly Skilled Migrant","5 years","EUR 320","IND-recognized sponsor, salary EUR 3,549+/month (30+)"),("Self-Employment","2 years","EUR 1,400","Points system, business plan, value to NL economy"),("Dutch-American Friendship (DAFT)","2 years","EUR 1,400","US citizens, EUR 4,500 investment")],"proc":[("Schengen C","15 days","EUR 80","Express: 5-10 days","EUR 80"),("MVV","1-3 months","EUR 210","N/A","N/A"),("Highly Skilled","2-4 weeks","EUR 320","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000 minimum. No mandatory vaccinations. TB screening required for work/residence permit (except EU/EEA nationals). Health insurance mandatory for residents (starting ~EUR 120/month). EU/EEA citizens: EHIC accepted for emergency care.","extension":"Schengen 90/180 rule. Residence permit renewable at IND. Overstay: fine up to EUR 4,000, entry ban 1-5 years, Schengen-wide alert.","refusal":"Common reasons: insufficient income proof, incomplete documents, doubts about return. Appeal through IND objection procedure (bezwaar) within 4 weeks, then to court (beroep). High success rate on appeal for work-related visas."},
"new-zealand": {"visas":[("Visitor Visa (visa-free)","90 days","Free","60+ nationalities via NZeTA ($17-23 + IVL $35)"),("NZeTA","Up to 90 days","NZD 17 (app) / $23 (web) + IVL $35","Required before boarding for visa-waiver nationals"),("Visitor Visa","9 months","NZD 246","For non-visa-waiver nationals"),("Working Holiday","1-2 years","NZD 455","Age 18-30 (35 some countries), bilateral agreement"),("Student Visa","Duration","NZD 395","Offer of place, financial proof NZD 20,000/year"),("Essential Skills Work Visa","3 years","NZD 495-765","Employer accredited, median wage+ for 3 years"),("Accredited Employer Work Visa","3 years","NZD 750","Accredited employer, job check, median wage+"),("Skilled Migrant Category (Resident)","Permanent","NZD 3,310","Points-based, 180 points, skilled employment"),("Parent Category","Permanent","NZD 3,310","Adult child sponsor, income threshold")],"proc":[("NZeTA","Minutes to 72 hours","NZD 17-23","N/A","N/A"),("Visitor","20-25 days","NZD 246","N/A","N/A"),("Student","25-30 days","NZD 395","N/A","N/A"),("Work","30-90 days","NZD 495-765","N/A","N/A")],"health":"No mandatory vaccinations but certain nationalities require medical and chest X-ray. TB screening for stays 6+ months (except low-risk countries). Health insurance strongly recommended - NZ has reciprocal healthcare agreements with UK and Australia only. INZ-approved panel physicians required for medical exams. Police clearance for stays 24+ months.","extension":"Visitor visa extendable at INZ, max 9 months in 18. Must apply before current visa expires. Overstay: section 289 deportation liability, 5-year entry ban. Voluntary departure reduces penalties. Must comply with visa conditions (no work on visitor visa).","refusal":"Common: insufficient funds, health concerns, character issues, genuine intent doubts. Appeal to Immigration and Protection Tribunal (IPT) for residence visas. Reconsideration request for other visas. Immigration advisers must be licensed by IAA."},
"nicaragua": {"visas":[("Visa-Free Entry","90 days","Free","Most Western nationalities"),("Tourist Card (CA-4)","90 days","$10-12","CA-4 agreement (shared with Guatemala, Honduras, El Salvador)"),("Business Visa","30 days","$50-100","Business invitation"),("Residency (Pensionado)","Renewable","$300-500","$600/month pension income")],"proc":[("Tourist","Instant","$10-12","N/A","N/A"),("Residency","2-3 months","$300-500","N/A","N/A")],"health":"No mandatory vaccinations. Yellow Fever certificate if from endemic area. Dengue and Zika present. Medical facilities limited. Travel insurance recommended.","extension":"CA-4 90-day period shared between Guatemala, Honduras, El Salvador, Nicaragua. Must exit CA-4 region for 72 hours to reset. Overstay fine: $2/day.","refusal":"Rare for tourists. May occur based on nationality. No formal appeal."},
"norway": {"visas":[("Schengen Short Stay","90 days in 180","Free or EUR 80","Visa-exempt for 60+ nationalities"),("Schengen Visa C","90 days","EUR 80 / NOK 800","Standard Schengen tourist/business"),("Work Permit (Skilled Worker)","1-3 years","NOK 6,300","Job offer, relevant qualifications, salary threshold"),("Student Permit","Duration","NOK 6,300","University admission, NOK 137,907/year funds"),("Family Reunification","1-3 years","NOK 12,500","Sponsor in Norway, income requirement NOK 321,800"),("Seasonal Worker","6 months","NOK 6,300","Agriculture/tourism sectors"),("Au Pair","2 years","NOK 6,300","Age 18-30, host family agreement")],"proc":[("Schengen C","15 days","EUR 80","Express: 5-7 days","EUR 80"),("Work Permit","1-3 months","NOK 6,300","N/A","N/A"),("Student","2-3 months","NOK 6,300","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000 minimum. No mandatory vaccinations. TB screening for certain nationalities. Norway has excellent public healthcare - residents access via National Insurance Scheme (folketrygden). EU/EEA: EHIC accepted.","extension":"Schengen 90/180 rule. Residence permits renewable at UDI. Apply 3 months before expiry. Overstay: deportation, Schengen-wide entry ban 1-5 years.","refusal":"Common: insufficient ties to home country, inadequate funds. Appeal to UNE (Immigration Appeals Board) within 3 weeks. High standards for work permit sponsorship."},
"oman": {"visas":[("Tourist e-Visa","10-30 days","OMR 5-20 (~$13-52)","Online for most nationalities"),("Visa on Arrival","14-30 days","OMR 5-20","Available for GCC residents and select nationalities"),("Express Visa","30 days","OMR 5","Available for select nationalities at border"),("Work Visa","2 years","OMR 200-500","Employer sponsorship, medical clearance"),("Family Visit","1 month","OMR 10","Sponsored by Oman resident"),("Business Visa","1 month","OMR 20","Company invitation")],"proc":[("e-Visa","1-3 days","OMR 5-20","N/A","N/A"),("VOA","Instant","OMR 5-20","N/A","N/A"),("Work","2-4 weeks","OMR 200-500","N/A","N/A")],"health":"Medical exam mandatory for work visa: HIV, Hepatitis B/C, TB, pregnancy test for women. Must be done at approved clinics. No vaccinations required for tourists. COVID-19 not required.","extension":"Tourist visa extendable once at ROP for additional 30 days. Overstay: OMR 10/day fine. Significant overstay: detention, deportation, 2-year entry ban.","refusal":"May occur for single women under 30 (some nationalities). Security screening for certain nationalities. No formal appeal."},
"panama": {"visas":[("Tourist Card","180 days","Free-$20","Most Western nationalities get 180 days"),("Tourist Visa (stamped)","90 days","$20","Required for some nationalities"),("Pensionado Visa","Renewable","$300-500","$1,000/month pension income, many discounts"),("Friendly Nations Visa","Permanent","$5,000-8,000","Citizens of 50 approved countries, $5,000 bank deposit"),("Self-Economic Solvency","Permanent","$5,000-8,000","$300,000 real estate OR $300,000 bank deposit"),("Digital Nomad (Short Stay)","9 months","$300","$3,000/month income, remote work for foreign company"),("Work Permit","1-2 years","$2,000-5,000","Employer sponsorship, labor test"),("Student Visa","Duration","$300-500","University acceptance")],"proc":[("Tourist","Instant","Free-$20","N/A","N/A"),("Pensionado","3-6 months","$300-500","N/A","N/A"),("Friendly Nations","3-6 months","$5,000-8,000","N/A","N/A")],"health":"No mandatory vaccinations except Yellow Fever if from endemic country. No health exam for tourists. Caja de Seguro Social (CSS) public healthcare for residents. Private healthcare good in Panama City. Health insurance required for pensionado visa.","extension":"Tourist 180-day stay can be extended by brief exit to Costa Rica/Colombia and return. Overstay: $50/month fine. Must regularize status or exit. No jail for overstay but deportation possible.","refusal":"Rare for eligible nationalities. May occur at border if suspected of working without permit. Friendly Nations visa may be refused for insufficient bank deposit or criminal record."},
"peru": {"visas":[("Visa-Free Entry","90-183 days","Free","90+ nationalities (90 or 183 days depending on country)"),("Tourist Visa","183 days","$30-65","For nationalities requiring visa"),("Business Visa","183 days","$30-65","Business invitation letter"),("Work Visa","1 year","$50-100","Employer sponsorship, TUPA procedures"),("Student Visa","Duration","$50-100","University acceptance"),("Investor Visa","1 year","$50-100","Investment in Peruvian business")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Tourist/Business","3-5 days","$30-65","N/A","N/A"),("Work","2-4 weeks","$50-100","N/A","N/A")],"health":"No mandatory vaccinations. Yellow Fever highly recommended for Amazon/jungle regions. Altitude sickness preparation for Cusco (3,400m). Medical facilities good in Lima, limited in rural areas. Travel insurance recommended.","extension":"Immigration officer assigns 30-183 days at entry. Extendable at Migraciones in Lima for S/. 50-100. Max 183 days. Overstay: $1/day fine, must pay before departure. No entry ban for minor overstay.","refusal":"Rare for visa-free nationals. May occur if suspected of working illegally. No formal appeal. Can re-enter after issues resolved."},
"philippines": {"visas":[("Visa-Free Entry","30 days","Free","157 nationalities"),("Visa on Arrival","30 days","Free","Extension up to 36 months possible"),("Tourist Visa Extension","Up to 36 months","PHP 3,030-5,000/month","At Bureau of Immigration, multiple extensions"),("Balikbayan Privilege","1 year","Free","Former Filipino citizens and their families"),("9(a) Temporary Visitor","59 days","$40-50","Embassy visa for nationals needing visa"),("9(g) Pre-arranged Employment","1-3 years","$200-500","Alien Employment Permit (AEP) from DOLE"),("SRRV (Special Resident Retiree)","Permanent","$1,500","Age 35+, $20,000-50,000 deposit"),("Student Visa (9f)","Duration","$200-300","School acceptance, ACR-I card")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Extension","Same day","PHP 3,030-5,000","N/A","N/A"),("SRRV","2-3 months","$1,500","N/A","N/A")],"health":"No mandatory vaccinations. Yellow Fever if from endemic area. Dengue present. Hepatitis A/B recommended. Medical facilities good in Manila/Cebu, limited elsewhere. ECC (Emigration Clearance Certificate) needed if staying 6+ months.","extension":"Visa-free 30 days extendable to 59 days (PHP 3,030), then monthly up to 36 months. Must get ACR-I Card after 59 days (PHP 3,300). Annual Report required if staying 1+ year. Overstay fine: PHP 1,000/month + penalties. Express lane available at BI for extra fee.","refusal":"Rare for visa-free entry. May be denied for: no return ticket, insufficient funds, blacklisted. Bureau of Immigration decisions can be appealed. Foreign nationals with overstay history may face additional scrutiny."},
"poland": {"visas":[("Schengen Short Stay","90 days in 180","Free or EUR 80","Standard Schengen rules"),("Schengen Visa C","90 days","EUR 80 / PLN 400","Tourist, business, family visit"),("National Visa D","1 year","EUR 80 / PLN 400","Work, study, family reunion"),("Work Permit (Type A)","3 years","PLN 100","Employer files at Voivodeship Office"),("Seasonal Work (Type S)","9 months","PLN 30","Agriculture/hospitality"),("Poland Business Harbour","1 year+","EUR 80","IT specialists from 6 countries, fast-track"),("Student Visa","Duration","EUR 80","University acceptance, PLN 7,500/year funds")],"proc":[("Schengen C","15 days","EUR 80","Express: 5-7 days","EUR 80"),("National D","1-2 months","EUR 80","N/A","N/A"),("Work Permit","1-2 months","PLN 100","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000 minimum. No mandatory vaccinations. Polish public healthcare (NFZ) for residents. EU/EEA: EHIC accepted. TB screening not required. Biometrics collected at VFS.","extension":"Schengen 90/180 rule. Temporary Residence Permit (TRP) from Voivodeship Office - apply before visa expires. Processing can take 3-6 months (interim stamp allows stay). Overstay: fine, deportation, Schengen entry ban.","refusal":"Common: weak ties to home, insufficient funds. Appeal to Consul within 14 days. Second rejection appealable to Minister of Foreign Affairs. Poland Business Harbour has higher acceptance rate."},
"portugal": {"visas":[("Schengen Short Stay","90 days in 180","Free or EUR 80","Standard Schengen visa rules"),("D7 Passive Income Visa","1-2 years","EUR 90","EUR 760/month minimum passive income (pension, rental, dividends)"),("D8 Digital Nomad Visa","1-2 years","EUR 90","EUR 3,040/month minimum income from remote work"),("Golden Visa","5 years","EUR 90 + investment","EUR 500,000 fund investment (real estate option removed 2023)"),("D2 Entrepreneur Visa","1-2 years","EUR 90","Business plan, investment, job creation"),("Student Visa","Duration","EUR 90","University acceptance, EUR 760/month funds"),("Tech Visa","1-2 years","EUR 90","Job offer from IAPMEI-certified company"),("Family Reunification","2 years","EUR 90","Sponsor with legal residence, income proof"),("NHR/IFICI Tax Regime","10 years","N/A","20% flat tax on Portuguese-source income")],"proc":[("Schengen C","15 days","EUR 80","Express: 5-7 days","EUR 80"),("D7","2-3 months","EUR 90","N/A","N/A"),("D8","2-3 months","EUR 90","N/A","N/A"),("Golden","4-6 months","EUR 90","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000 minimum. No mandatory vaccinations. Portugal SNS (public healthcare) free for residents. Private insurance required for D7/D8 visa application (Medis, Multicare). TB screening not required. EHIC for EU citizens. Excellent healthcare quality (ranked 12th globally).","extension":"Schengen 90/180 rule. D7/D8 residence permit renewable at AIMA (ex-SEF). Apply 30 days before expiry. Path to permanent residency after 5 years, citizenship after 5 years (one of shortest in EU). Overstay: fine, deportation, Schengen ban.","refusal":"Common: insufficient income proof, incomplete NIF (tax number), no Portuguese bank account. Appeal to Administrative Court within 15 days. D7 requires showing passive income BEFORE application. Golden Visa has high acceptance rate. Engaging a Portuguese immigration lawyer (advogado) recommended."},
"qatar": {"visas":[("Visa-Free Entry","30-90 days","Free","80+ nationalities (30 or 90 days)"),("Hayya Card","Varies","Free","For events/visitors, digital entry permit"),("Tourist Visa","30 days","QAR 100 (~$27)","For nationalities not eligible for visa-free"),("Business Visa","30 days","QAR 200","Company sponsor in Qatar"),("Work Visa (Residence Permit)","2 years","QAR 200-1,000","Employer sponsorship, medical clearance"),("Family Visit","1-3 months","QAR 200","Sponsored by Qatar resident"),("GCC Resident Visa","30 days","QAR 100","For residents of other GCC countries")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Tourist","2-3 days","QAR 100","N/A","N/A"),("Work","2-4 weeks","QAR 200-1,000","N/A","N/A")],"health":"Medical exam mandatory for work/residence visa: HIV, Hepatitis B/C, TB, chest X-ray. Must be done at approved medical commission. No vaccinations required for tourists. Health insurance provided by employer for workers.","extension":"Tourist visa extendable once for 30 days at MOI. Overstay: QAR 200/day fine. Significant overstay: detention, deportation, entry ban. Exit permit system abolished in 2020 for most workers.","refusal":"May occur for: certain nationalities, security screening, previous violations. No formal appeal for tourist visa. Work visa depends on employer sponsorship and quota."},
"romania": {"visas":[("Short Stay","90 days in 180","Free or EUR 80","Not yet in Schengen area but accepts Schengen visas"),("Airport Transit","N/A","EUR 80","For transit passengers"),("Long Stay Visa D","1 year","EUR 120","Work, study, family, business"),("Work Permit","1 year","EUR 120","Employer sponsorship through IGI"),("Student Visa","Duration","EUR 120","University acceptance"),("Digital Nomad Visa","1 year","EUR 120 + EUR 100","EUR 3,700/month income, remote work")],"proc":[("Short Stay","15 days","Free-EUR 80","N/A","N/A"),("Long Stay D","1-2 months","EUR 120","N/A","N/A"),("Work","1-3 months","EUR 120","N/A","N/A")],"health":"No mandatory vaccinations. Travel health insurance recommended. Romania joining Schengen air borders March 2024, land borders pending. Good healthcare in Bucharest, variable elsewhere.","extension":"90-day stay not extendable without long-stay visa. Apply for residence permit at IGI after D visa. Overstay: fine, deportation. Romania joining Schengen will change rules.","refusal":"Standard European refusal reasons. Appeal to court within 30 days. Romania has moderate acceptance rate for visas."},
"samoa": {"visas":[("Visitor Permit","60 days","Free","Permit issued on arrival for most nationalities"),("Business Visitor","30 days","Free-WST 100","Business purpose documentation"),("Work Permit","1-2 years","WST 200-500","Employer sponsorship, Cabinet approval"),("Student Permit","Duration","WST 100","School acceptance")],"proc":[("Visitor","Instant","Free","N/A","N/A"),("Work","4-8 weeks","WST 200-500","N/A","N/A")],"health":"No mandatory vaccinations but Hepatitis A/B recommended. Measles/MMR recommended. Limited medical facilities - evacuation to New Zealand for serious cases.","extension":"60-day visitor permit extendable at Immigration Office in Apia for additional 60 days. Overstay: WST 500 fine.","refusal":"Rare for tourists. Work permits competitive and limited."},
"saudi-arabia": {"visas":[("Tourist e-Visa","90 days","SAR 480 (~$128)","49 eligible nationalities, online application"),("Visa on Arrival","90 days","SAR 480","For e-Visa eligible nationalities at airports"),("Umrah Visa","30-90 days","Free-$133","For religious pilgrimage, via authorized agents"),("Hajj Visa","30 days","$133-500","For annual Hajj pilgrimage, quota system by country"),("Business Visit","90 days","SAR 400-800","Company sponsor/invitation"),("Work Visa (Iqama)","1-2 years","SAR 650-2,000","Employer sponsorship, medical clearance, Nitaqat compliance"),("Family Visit","90-180 days","SAR 200-500","Sponsored by Iqama holder"),("Premium Residency","Permanent","SAR 800,000 (~$213k)","No sponsor required, full rights")],"proc":[("e-Visa","5-30 minutes","SAR 480","N/A","N/A"),("Umrah","3-7 days","Free-$133","N/A","N/A"),("Work","2-6 weeks","SAR 650-2,000","N/A","N/A")],"health":"Medical exam mandatory for work visa: HIV, Hepatitis B/C, TB, VDRL. Meningitis (ACWY) vaccination mandatory for Hajj/Umrah. No COVID-19 vaccination required. Health insurance mandatory for Iqama holders.","extension":"Tourist e-Visa: max 90 days per visit, 1 year validity, multiple entries. Work visa renewal through employer. Overstay: SAR 100/day first time, SAR 200/day repeat, deportation, 3-year entry ban.","refusal":"e-Visa has high acceptance rate for eligible nationalities. Work visa depends on Nitaqat Saudization quotas. Israeli passport holders/stamps may face issues. No formal appeal for tourist visa refusal."},
"singapore": {"visas":[("Visa-Free Entry","30-90 days","Free","150+ nationalities (most get 30 days)"),("SG Arrival Card (SGAC)","N/A","Free","Mandatory for ALL travelers - online form within 3 days of arrival"),("Tourist Visa","30 days","SGD 30","For nationalities requiring visa"),("Employment Pass (EP)","2 years","SGD 105","Min salary SGD 5,000/month (financial sector: SGD 5,500)"),("S Pass","2 years","SGD 60","Skilled workers, min SGD 3,150/month, levy applies"),("Entrepass","1-2 years","SGD 105","Entrepreneurs, funded startup or innovative business"),("Student Pass","Duration","SGD 30","Accepted by approved institution"),("Dependant Pass","Duration","SGD 105","Spouse/children of EP holder, min salary SGD 6,000"),("Long-Term Visit Pass (LTVP)","1-5 years","SGD 105","Common-law spouse, elderly parents"),("Work Holiday","6 months","Free","Age 18-25, select universities")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Tourist","3-5 days","SGD 30","N/A","N/A"),("EP","3-8 weeks","SGD 105","N/A","N/A"),("S Pass","3-8 weeks","SGD 60","N/A","N/A")],"health":"No mandatory vaccinations except Yellow Fever if from endemic area. SGAC (SG Arrival Card) mandatory for all arrivals - free, online, within 3 days before arrival. No health exam for tourists. Work/EP holders may need medical exam. Singapore has world-class healthcare (ranked 6th globally). Medishield Life for residents.","extension":"30-day stay extendable at ICA for additional 30 days (SGD 40). Maximum 89 days on tourist visit. EP/S Pass renewal through employer via EP Online. Overstay: jail up to 6 months, fine up to SGD 6,000, mandatory caning (3+ strokes) for overstay >90 days. Singapore has extremely strict immigration enforcement.","refusal":"Strict entry criteria. Common refusals: suspected working without permit, inadequate funds, previous violations, drug-related offenses (zero tolerance). No formal appeal for visitor entry refusal. EP refusals can be appealed to MOM. Drug trafficking carries mandatory death penalty - never carry drugs."},
"slovakia": {"visas":[("Schengen Short Stay","90 days in 180","Free or EUR 80","Standard Schengen rules"),("Schengen Visa C","90 days","EUR 80","Tourist, business, family visit"),("National Visa D","1 year","EUR 35","Work, study, family"),("Work Permit","2 years","EUR 165.50","Employer sponsorship"),("Student Visa","Duration","EUR 35","University acceptance")],"proc":[("Schengen C","15 days","EUR 80","Express: 5-7 days","EUR 80"),("National D","1-2 months","EUR 35","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000. No mandatory vaccinations. Slovak public healthcare (VSZP) for residents. EHIC for EU citizens.","extension":"Schengen 90/180 rule. Temporary residence at Foreign Police within 3 days. Overstay: fine, deportation, Schengen ban.","refusal":"Standard Schengen grounds. Appeal to Ministry of Foreign Affairs within 15 days."},
"slovenia": {"visas":[("Schengen Short Stay","90 days in 180","Free or EUR 80","Standard Schengen rules"),("Schengen Visa C","90 days","EUR 80","Tourist, business, family visit"),("National Visa D","1 year","EUR 77","Work, study, family"),("Work Permit","1-2 years","EUR 77","Employer sponsorship"),("Digital Nomad Visa","1 year","EUR 77","EUR 2,535/month income")],"proc":[("Schengen C","15 days","EUR 80","Express: 5-7 days","EUR 80"),("National D","1-2 months","EUR 77","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000. No mandatory vaccinations. Slovenian ZZZS healthcare for residents. EHIC for EU citizens.","extension":"Schengen 90/180 rule. Register at Administrative Unit within 3 days. Overstay: fine EUR 500-1,200, deportation.","refusal":"Standard Schengen grounds. Appeal within 8 days to Ministry of Foreign Affairs."},
"south-korea": {"visas":[("Visa-Free Entry","30-90 days","Free","112 nationalities (most get 90 days)"),("K-ETA","N/A","KRW 10,000 (~$7)","Currently SUSPENDED until Dec 2025 for 22 countries"),("Tourist Visa C-3","90 days","$40-80","For nationalities requiring visa"),("Work Visa E-7","1-3 years","$80-120","Employer sponsorship, specialized skills"),("Teaching Visa E-2","1 year","$60","English teaching, degree + TEFL, criminal check"),("Student Visa D-2","Duration","$60","University acceptance, financial proof KRW 20M+"),("D-10 Job Seeking","6 months","$60","Recent graduates from Korean universities"),("F-2 Residence","3 years","$60","Points-based (80+ points), long-term workers"),("F-5 Permanent Residence","Permanent","$200","5+ years, Korean proficiency (TOPIK 4+), income"),("Working Holiday H-1","1 year","$60","Age 18-30, bilateral agreement countries")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Tourist C-3","5-7 days","$40-80","Express: 2-3 days","$80-120"),("Work E-7","2-4 weeks","$80-120","N/A","N/A"),("Student D-2","2-4 weeks","$60","N/A","N/A")],"health":"No mandatory vaccinations. K-ETA currently suspended for most visa-free nationals. TB screening for E-2 (teaching) visa. Medical exam for work visa at designated hospitals. Korean NHI (National Health Insurance) mandatory for residents - 3.495% of income. No COVID-19 requirements.","extension":"Visa-free 90 days not extendable. Visa holders extend at Hi Korea (immigration office) before expiry. Overstay: KRW 200,000-500,000 fine, detention, deportation, 1-5 year re-entry ban. Report departure 48h in advance.","refusal":"Common: insufficient financial proof, unclear purpose, previous overstay in Korea/Japan. Appeal to Ministry of Justice within 14 days. Reapplication possible after 3 months. Teaching visa requires clean criminal background check."},
"spain": {"visas":[("Schengen Short Stay","90 days in 180","Free or EUR 80","Standard Schengen rules"),("Non-Lucrative Visa","1 year","EUR 80","EUR 2,400/month (individual), no work allowed in Spain"),("Digital Nomad Visa","3 years","EUR 80","EUR 2,646/month income, remote work for foreign company"),("Golden Visa","2-5 years","EUR 80 + investment","EUR 500,000 real estate (under review) or EUR 1M business"),("Student Visa","Duration","EUR 80","University acceptance, EUR 600/month funds"),("Work Visa","1 year","EUR 80","Employer sponsorship, labor market test"),("Self-Employment (Autonomo)","1 year","EUR 80","Business plan, EUR 30,000+ investment, relevant experience"),("Family Reunification","1 year","EUR 80","Sponsor with 1+ year residence, income 150% IPREM"),("Beckham Law Tax Regime","6 years","N/A","24% flat tax on Spanish income (vs 47% progressive)")],"proc":[("Schengen C","15 days","EUR 80","Express: 5-7 days","EUR 80"),("Non-Lucrative","1-3 months","EUR 80","N/A","N/A"),("Digital Nomad","20 days","EUR 80","N/A","N/A"),("Golden","2-3 months","EUR 80","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000 minimum. No mandatory vaccinations. Spanish public healthcare (SAS) excellent for residents with Social Security registration. Private insurance required for Non-Lucrative and Digital Nomad visa applications (Sanitas, Adeslas, Asisa from EUR 50/month). EHIC for EU citizens.","extension":"Schengen 90/180 rule. Non-Lucrative renewable for 2 years at Foreigners Office. Digital Nomad renewable for 3 years. Path to permanent residency after 5 years. Spanish citizenship after 10 years (2 years for Latin American nationals). Overstay: fine EUR 501-10,000, deportation, Schengen ban.","refusal":"Common: insufficient income proof (Non-Lucrative requires EUR 2,400/month minimum), incomplete documents, health insurance not meeting requirements. Appeal (recurso de reposicion) within 1 month to consulate, then to Audiencia Nacional. Digital Nomad visa has high acceptance rate. Beckham Law requires applying within 6 months of becoming tax resident."},
"sri-lanka": {"visas":[("ETA (Electronic Travel Authorization)","30 days","Free (tourism)","Free since 2024 for tourism. Apply online before travel"),("Tourist Visa Extension","Up to 90 days","$25-50","Extendable at Department of Immigration, Colombo"),("Business ETA","30 days","$50","Business activities, conferences"),("Transit ETA","48 hours","Free","Transit passengers connecting through Colombo"),("Residence Visa","1 year","$200-500","Employment, study, NGO work"),("Investor Visa","5 years","$5,000","$250,000+ investment in Sri Lanka")],"proc":[("ETA","24-48 hours","Free","N/A","N/A"),("Business ETA","24-48 hours","$50","N/A","N/A"),("Residence","2-4 weeks","$200-500","N/A","N/A")],"health":"No mandatory vaccinations except Yellow Fever if from endemic area. Dengue present. Hepatitis A/B recommended. Medical facilities adequate in Colombo (Lanka Hospitals, Nawaloka). Limited elsewhere. Travel insurance recommended.","extension":"ETA 30 days extendable twice at Department of Immigration in Colombo for total 90 days. $25 for first extension. Overstay: $25/day fine. Significant overstay: detention, deportation.","refusal":"ETA rarely refused for eligible nationalities. May be denied for: previous immigration violations, security concerns. No formal appeal. Can reapply online."},
"sweden": {"visas":[("Schengen Short Stay","90 days in 180","Free or EUR 80","Standard Schengen rules"),("Schengen Visa C","90 days","SEK 900","Tourist, business, family visit"),("Work Permit","2 years","SEK 2,000","Job offer, min SEK 27,360/month, union-level terms"),("Student Residence Permit","Duration","SEK 1,500","University admission, SEK 10,314/month funds"),("Family Reunification","2 years","SEK 2,000","Sponsor income requirement, cohabitation proof"),("Self-Employment","2 years","SEK 2,000","Viable business plan, SEK 200,000+ capital"),("Working Holiday","1 year","SEK 1,500","Age 18-30, bilateral agreement (Australia, NZ, Canada, etc.)"),("Researcher Permit","2 years","SEK 2,000","Research agreement with Swedish institution")],"proc":[("Schengen C","15 days","SEK 900","Express: 5-7 days","SEK 900"),("Work Permit","1-4 months","SEK 2,000","N/A","N/A"),("Student","2-3 months","SEK 1,500","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000 minimum. No mandatory vaccinations. Swedish public healthcare excellent for registered residents (personnummer required). EU/EEA: EHIC accepted. Workers must register at Skatteverket for personnummer.","extension":"Schengen 90/180 rule. Work/study permit renewal at Migrationsverket 30 days before expiry. Online application possible. Permanent residence after 4 years of work permit. Swedish citizenship after 5 years. Overstay: deportation, Schengen ban, fine.","refusal":"Common: salary below SEK 27,360/month threshold, employer not meeting conditions, insufficient study funds. Appeal to Migrationsoverdomstolen (Migration Court of Appeal) within 3 weeks. Sweden has strict labor market requirements for work permits."},
"switzerland": {"visas":[("Schengen Short Stay","90 days in 180","Free or CHF 80","Visa-exempt for 60+ nationalities"),("Schengen Visa C","90 days","CHF 80","Tourist, business, family visit"),("National Visa D","6+ months","CHF 90","Work, study, family reunion"),("L Permit (Short-term)","Up to 1 year","CHF 90","Temporary work, specific project"),("B Permit (Residence)","1 year renewable","CHF 90","Employment, self-employment, study"),("C Permit (Settlement)","5 years renewable","CHF 90","After 5-10 years of B permit (nationality dependent)"),("G Permit (Cross-border)","5 years","CHF 90","Work in Switzerland, live in neighboring country")],"proc":[("Schengen C","10-15 days","CHF 80","Express: 5-7 days","CHF 80"),("National D/B Permit","4-8 weeks","CHF 90","N/A","N/A")],"health":"Schengen travel insurance EUR 30,000 minimum. No mandatory vaccinations. Swiss health insurance (Grundversicherung) mandatory for all residents within 3 months of arrival - CHF 300-500/month. Excellent healthcare (ranked 2nd globally). EU/EEA: EHIC for emergency only.","extension":"Schengen 90/180 rule. B Permit renewable at cantonal migration office. C Permit after 5 years (EU/EFTA) or 10 years (others). Swiss citizenship after 10 years of residence. Overstay: fine CHF 500-10,000, deportation, Schengen ban.","refusal":"Common: insufficient salary/qualifications for B permit, cantonal quota exceeded, weak ties. Appeal to Bundesverwaltungsgericht (Federal Administrative Court) within 30 days. Swiss immigration is among the strictest in Europe for non-EU nationals."},
"taiwan": {"visas":[("Visa-Free Entry","30-90 days","Free","46 nationalities (mostly 90 days)"),("Landing Visa","30 days","NTD 2,400 (~$75)","Select nationalities at airports"),("Visitor Visa (Single)","60 days","$50-76","Embassy/TECO application"),("Resident Visa","Duration","$66","Employment, study, family, investment"),("Employment Gold Card","1-3 years","NTD 3,600-4,000","Top talent in 8 fields, no employer needed"),("Work Permit","1-3 years","NTD 500","Employer sponsorship, min salary NTD 47,971/month"),("Student Visa","Duration","$50","University acceptance"),("Entrepreneur Visa","1 year","NTD 1,000","Startup plan, NTD 2M+ capital OR innovation")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Visitor","5-7 days","$50-76","Express: 2-3 days","$76-100"),("Gold Card","30 days","NTD 3,600-4,000","N/A","N/A")],"health":"No mandatory vaccinations. No health exam for tourists. National Health Insurance (NHI) for residents after 6 months - NTD 749/month base, covers 97% of medical costs. Taiwan has excellent healthcare (ranked 1st in some indexes). ARC holders must wait 6 months for NHI.","extension":"Visa-free 90 days extendable once for 90 days at NIA (National Immigration Agency). Maximum 180 days. Overstay: NTD 2,000-10,000 fine, deportation, entry ban 1-3 years. Gold Card holders can stay indefinitely during validity.","refusal":"Rare for visa-free nationals. Common for work visa: salary below threshold, employer issues. Appeal to MOFA within 30 days. Gold Card has high acceptance for qualifying professionals."},
"thailand": {"visas":[("Visa Exempt Entry","30-60 days","Free","93 nationalities (30 or 60 days depending on country)"),("Tourist Visa (TR)","60 days","THB 1,000 (~$28)","Single entry, extendable 30 days at immigration"),("TDAC Registration","N/A","Free","MANDATORY for all travelers - register at tdac.immigration.go.th before arrival"),("LTR Visa (Long-Term Resident)","10 years","$10,000 one-time","$80,000/year income OR $250,000 in assets. Digital nomads and retirees."),("Non-Immigrant O-A (Retirement)","1 year","THB 2,000","Age 50+, 800,000 THB in Thai bank OR 65,000 THB/month income"),("Non-Immigrant B (Business)","1 year","THB 2,000","Work permit required, employer sponsorship"),("Non-Immigrant ED (Education)","1 year","THB 2,000","Enrolled in Thai school/university/language course"),("Non-Immigrant O (Family)","1 year","THB 2,000","Married to Thai or parent of Thai child, 400,000 THB or 40,000 THB/month"),("Thailand Elite (Privilege)","5-20 years","THB 600,000-2M","Premium membership, no income requirement, VIP airport"),("Destination Thailand Visa (DTV)","5 years","THB 10,000","Digital nomad/remote worker, 500,000 THB income, multiple entry")],"proc":[("Visa exempt","Instant","Free","N/A","N/A"),("Tourist TR","1-3 days","THB 1,000","Express: same day","THB 1,200-1,500"),("LTR","20 business days","$10,000","N/A","N/A"),("Non-Imm O-A","5-10 days","THB 2,000","N/A","N/A"),("Elite","1-2 weeks","THB 600,000-2M","N/A","N/A")],"health":"No mandatory vaccinations. COVID-19 not required. Health insurance MANDATORY for Retirement O-A visa: minimum 40,000 THB outpatient / 400,000 THB inpatient coverage. LTR visa: $50,000+ health coverage. Thailand has world-class private hospitals (Bumrungrad, Samitivej, Bangkok Hospital). Public hospitals affordable but crowded.","extension":"Visa exempt 30/60 days extendable once for 30 days at Immigration (THB 1,900). Tourist visa 60 days extendable 30 days. Non-Immigrant visas renewable annually. 90-day reporting mandatory for all long-stay visa holders (online, mail, or in person). Overstay: THB 500/day fine (max 20,000), detention, deportation, re-entry ban 1-10 years depending on duration. Blacklist for serious overstays.","refusal":"Common: insufficient funds, suspected working on tourist visa, frequent border runs. Border refusal possible if too many entries. Embassy visa refusals can be reconsidered with additional documentation. No formal appeal process. Thailand immigration has discretion to refuse entry."},
"tonga": {"visas":[("Visitor Permit","30 days","Free","Most nationalities on arrival"),("Business Visitor","30 days","TOP 150","Business documentation"),("Work Permit","1-2 years","TOP 300-500","Employer sponsorship, Cabinet approval")],"proc":[("Visitor","Instant","Free","N/A","N/A"),("Work","4-8 weeks","TOP 300-500","N/A","N/A")],"health":"No mandatory vaccinations but Hepatitis A/B recommended. Limited medical facilities - evacuation to New Zealand/Australia for serious cases.","extension":"30-day visitor permit extendable at Immigration in Nuku'alofa. Overstay: TOP 500 fine.","refusal":"Rare for tourists. Work permits limited and competitive."},
"turkey": {"visas":[("e-Visa","30-90 days","$20-60","100+ nationalities, instant online approval at evisa.gov.tr"),("Visa-Free Entry","30-90 days","Free","90+ nationalities (most EU, Latin America, Japan, etc.)"),("Tourist Visa (Embassy)","90 days","$40-80","For nationalities not eligible for e-Visa"),("Residence Permit (Ikamet)","1-2 years","TRY 500-2,000","Rental contract, health insurance, financial proof"),("Work Permit","1-3 years","TRY 1,000-5,000","Employer sponsorship through Ministry of Labor"),("Student Visa","Duration","TRY 500","University acceptance, financial proof"),("Family Residence","2 years","TRY 500-1,000","Spouse/children of Turkish citizen or resident"),("Turquoise Card","Permanent","TRY 2,000","Exceptional talent, investors ($500,000+ investment)"),("Turkish Citizenship by Investment","Permanent","$400,000+","$400,000 property OR $500,000 deposit")],"proc":[("e-Visa","Minutes","$20-60","N/A","N/A"),("Residence","1-3 months","TRY 500-2,000","N/A","N/A"),("Work","1-2 months","TRY 1,000-5,000","N/A","N/A")],"health":"No mandatory vaccinations. e-Visa is instant online. Turkish public healthcare (SGK) for insured residents. Private healthcare excellent in Istanbul, Ankara (Acibadem, Florence Nightingale, Memorial hospitals). Health insurance required for residence permit (Dask + private from TRY 3,000-10,000/year).","extension":"e-Visa/tourist stay NOT extendable beyond visa duration. Must apply for residence permit (ikamet) within 10 days of arrival for long stays. Tourist visa: max 90 days in 180. Overstay: fine TRY 500-1,000+, deportation for significant overstay. V-number (visa violation) on record affects future applications.","refusal":"e-Visa rarely refused for eligible nationalities. Residence permit refusals: insufficient income, no valid rental contract, expired insurance. Appeal to Administrative Court within 60 days. Reapplication possible. Turkish immigration becoming stricter in Istanbul due to volume."},
"uae": {"visas":[("Visa-Free Entry","30-90 days","Free","70+ nationalities (most Western, GCC countries)"),("Tourist Visa (sponsor)","30-90 days","AED 300-1,100 (~$82-300)","Hotel or airline sponsorship"),("Visit Visa","30-90 days","AED 300-500","Sponsored by UAE resident"),("Employment Visa","2-3 years","AED 300-1,000","Employer sponsorship, Emirates ID, medical"),("Golden Visa","10 years","AED 2,000-3,000","Property AED 2M+ OR salary AED 30,000+/month OR investors/entrepreneurs"),("Green Visa","5 years","AED 1,000-2,000","Self-sponsored, freelancers AED 360,000/year, skilled workers AED 15,000/month"),("Freelance Permit","1-3 years","AED 7,500-15,000","Via free zones (DMCC, IFZA, etc.)"),("Student Visa","Duration","AED 300","University acceptance in UAE"),("Retirement Visa","5 years","AED 500","Age 55+, property AED 2M OR savings AED 1M OR AED 20,000/month income"),("Remote Work Visa","1 year","AED 1,627","$5,000/month income or equivalent, remote work for foreign company")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Tourist","2-5 days","AED 300-1,100","Express: 24 hours","AED 500-1,500"),("Employment","2-4 weeks","AED 300-1,000","N/A","N/A"),("Golden","2-4 weeks","AED 2,000-3,000","N/A","N/A")],"health":"Medical exam mandatory for employment/residence visa: chest X-ray, blood test (HIV, Hepatitis B/C, TB). Must be done at DHA-approved centers. Health insurance mandatory in Abu Dhabi and Dubai for all residents. No vaccinations required for tourists. UAE has world-class private healthcare (Cleveland Clinic AD, Mediclinic, NMC).","extension":"Visa-free 30 days extendable once for 30 additional days (AED 600). Tourist visa extendable through sponsor. Overstay: AED 50/day first 6 months, then AED 100/day. Grace period of 30 days after visa expiry to exit. Overstayers can face fines up to AED 100,000+, detention, deportation, entry ban.","refusal":"Visa-free entry rarely refused. Tourist/visit visa depends on sponsor credibility. Employment visa: medical failure (HIV, TB, Hepatitis B positive = automatic refusal and deportation). No formal appeal for entry refusal. Can reapply through different sponsor. Security screening for certain nationalities."},
"ukraine": {"visas":[("Visa-Free Entry","90 days in 180","Free","70+ nationalities (EU, USA, UK, Canada, etc.)"),("Type C Visa","90 days","$65-85","Tourist, business, family visit"),("Type D Visa","90 days (entry)","$65-85","Long-stay: work, study, family"),("Temporary Residence Permit","1 year","UAH 3,400","Employment, study, family, investment"),("Permanent Residence","Permanent","UAH 3,400","After 5 years TRP or marriage to Ukrainian")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Type C","5-10 days","$65-85","Express: 2-3 days","$130"),("Type D","10-15 days","$65-85","N/A","N/A")],"health":"No mandatory vaccinations. Health insurance recommended. Medical facilities adequate in Kyiv, limited elsewhere. Note: travel advisories may be in effect due to conflict situation. Check government travel warnings before planning travel.","extension":"90-day visa-free not extendable. Type D allows TRP application in Ukraine. Overstay: fine, deportation, 5-year entry ban.","refusal":"May occur based on nationality, security concerns, conflict zone proximity. No formal appeal. Check current travel advisories."},
"united-kingdom": {"visas":[("Visa-Free Entry","6 months","Free","Most EU/EEA, USA, Canada, Australia, Japan, etc."),("UK ETA","N/A","GBP 10","Rolling out 2024-2025 for non-visa nationals (Gulf states first)"),("Standard Visitor Visa","6 months","GBP 115","For nationalities requiring visa"),("Skilled Worker Visa","5 years","GBP 719-1,420","Employer sponsorship, min GBP 38,700/salary or going rate"),("Global Talent Visa","5 years","GBP 623","Endorsed by approved body, no employer needed"),("Student Visa","Duration + 4 months","GBP 490","CAS from licensed sponsor, GBP 1,334/month funds (London)"),("Graduate Visa","2-3 years","GBP 822","Post-study work, completed UK degree"),("Innovator Founder","3 years","GBP 1,191","Innovative business, endorsed by approved body"),("Family Visa","2.5 years","GBP 1,846","Partner/spouse of British citizen, income GBP 29,000/year"),("Youth Mobility (T5)","2 years","GBP 298","Age 18-30, participating countries"),("Ancestry Visa","5 years","GBP 718","UK-born grandparent, Commonwealth citizens")],"proc":[("Visitor","3 weeks","GBP 115","Priority: 5 days","GBP 500"),("Skilled Worker","3-8 weeks","GBP 719-1,420","Priority: 5 days","GBP 500"),("Student","3-6 weeks","GBP 490","Priority: 5 days","GBP 500"),("Global Talent","5-8 weeks","GBP 623","N/A","N/A")],"health":"No mandatory vaccinations. TB screening required for nationals of high-TB countries (stays 6+ months). Immigration Health Surcharge (IHS) mandatory for all visa holders: GBP 1,035/year. Provides NHS access. UK ETA rolling out progressively. Biometrics (fingerprints + photo) at VAC for all visa applications.","extension":"Visitor visa NOT extendable (except exceptional circumstances). Work/student visa renewable before expiry. Overstay: illegal from day 1 after visa expires. Reported to Home Office, future visa applications affected, 10-year re-entry ban for overstay. Voluntary departure within 30 days of overstay: 1-year re-entry ban.","refusal":"Common: insufficient funds, weak ties to home country, previous refusal/overstay. Immigration Health Surcharge not paid. Appeal to First-tier Tribunal for human rights claims only. Most visitor refusals: administrative review (GBP 80) within 28 days. Skilled Worker refusals: sponsor license issues. Engaging OISC-registered immigration adviser recommended."},
"uruguay": {"visas":[("Visa-Free Entry","90 days","Free","Most Western nationalities, extended to 90 days"),("Tourist Visa","90 days","$40-65","For nationalities requiring visa"),("Temporary Residence","1-2 years","$100-300","Employment, family, retirement"),("Permanent Residence","Permanent","$200-500","After 3 years temporary or 5 years residence")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("Temporary Residence","2-3 months","$100-300","N/A","N/A")],"health":"No mandatory vaccinations. Uruguay has excellent public healthcare (ASSE/mutualistas). Health insurance (mutualista) ~$100-200/month for residents. No COVID-19 requirements.","extension":"90-day stay extendable at Migraciones for additional 90 days. Overstay: fine, must regularize status before departure.","refusal":"Very rare for tourists. Uruguay has open immigration policy. Residence straightforward."},
"usa": {"visas":[("Visa Waiver Program / ESTA","90 days","$21","42 VWP countries. ESTA mandatory before travel."),("B-1/B-2 Tourist/Business","6 months","$185","Non-VWP nationals, embassy interview required"),("F-1 Student","Duration of studies + OPT","$185","SEVIS I-20, financial proof $30,000+/year, embassy interview"),("J-1 Exchange Visitor","1-3 years","$185","DS-2019 from sponsor organization"),("H-1B Skilled Worker","3 years (ext. to 6)","$460-4,460","Employer petition, specialty occupation, lottery system (cap 85,000/year)"),("L-1 Intracompany Transfer","1-3 years","$460-4,460","1 year with foreign office of US company"),("O-1 Extraordinary Ability","3 years","$460","Extraordinary ability in sciences, arts, business, athletics"),("E-2 Treaty Investor","5 years","$315","$100,000+ investment, treaty country national"),("EB-5 Immigrant Investor","Permanent","$3,675","$800,000-1,050,000 investment, create 10 jobs"),("K-1 Fiance(e)","90 days to marry","$535","US citizen fiance, met in person within 2 years"),("Green Card (Immigrant)","Permanent","$325-1,225","Family/employment/diversity lottery sponsorship")],"proc":[("ESTA","Minutes to 72 hours","$21","N/A","N/A"),("B-1/B-2","3-6 months (incl. interview)","$185","N/A","N/A"),("F-1","2-4 months","$185 + SEVIS $350","N/A","N/A"),("H-1B","3-6 months","$460-4,460","Premium: 15 days","$2,805")],"health":"No mandatory vaccinations for tourists/B-1/B-2. Immigrant visa (Green Card) applicants: USCIS civil surgeon exam + vaccinations (MMR, Tdap, Varicella, Influenza, COVID-19 per CDC schedule). No public healthcare - travel insurance essential. US healthcare extremely expensive without insurance. ESTA applicants: no health exam.","extension":"B-1/B-2 extendable at USCIS (I-539) for 6 months (processing 6-12 months). ESTA/VWP NOT extendable - must leave within 90 days. F-1 students: status maintained as long as enrolled + OPT. H-1B: extendable to 6 years, beyond with I-140 pending. Overstay consequences severe: 180+ days = 3-year entry bar, 1+ year = 10-year bar. Any overstay = ESTA ineligibility permanently, must apply for visa at embassy.","refusal":"B-1/B-2 refusal rate varies by country (10-80%). Common: 214(b) - failure to demonstrate strong ties to home country. No appeal for 214(b) refusal. Can reapply anytime with new evidence. H-1B: lottery system means most applications rejected (registration: 300,000+ for 85,000 slots). Student visa: funding concerns, program legitimacy. Waiver of ineligibility (212) possible for some grounds."},
"venezuela": {"visas":[("Visa-Free Entry","90 days","Free","Mercosur nationals, some Caribbean countries"),("Tourist Visa","90 days","$30-60","Most nationalities require embassy visa"),("Business Visa","90 days","$60","Company invitation letter"),("Work Visa","1 year","$100-200","Employer sponsorship"),("Transit Visa","72 hours","$30","Transit passengers")],"proc":[("Tourist","5-10 days","$30-60","N/A","N/A"),("Work","2-4 weeks","$100-200","N/A","N/A")],"health":"Yellow Fever vaccination recommended for some areas. Medical facilities limited. Travel insurance essential. Check current travel advisories - political situation may affect travel.","extension":"90-day stay may be extended at SAIME (immigration). Overstay: fine, potential deportation.","refusal":"May occur based on nationality, political situation. Check current travel advisories. Embassy appointments may be difficult to obtain."},
"vietnam": {"visas":[("Visa-Free Entry","15-45 days","Free","25 nationalities (most get 45 days since 2023)"),("e-Visa","30 days (single entry)","$25","90+ nationalities, online at evisa.xuatnhapcanh.gov.vn"),("Visa on Arrival","30-90 days","$25-50 + $25-50 stamp fee","Pre-arranged approval letter + stamp at airport"),("Tourist Visa (Embassy)","30-90 days","$25-80","Single or multiple entry"),("Business Visa","30-90 days","$25-80","Business invitation from Vietnamese company"),("Work Permit","2 years","$100-400","Employer sponsorship, qualification verification"),("Investor Visa","Duration","$100-500","Investment in Vietnamese company"),("Student Visa","Duration","$25-50","University acceptance letter"),("Temporary Residence Card","1-2 years","$100-300","For work permit/investor visa holders")],"proc":[("Visa-free","Instant","Free","N/A","N/A"),("e-Visa","3 business days","$25","N/A","N/A"),("VOA letter","1-2 days","$25-50 + stamp fee","Express: 4-8 hours","$50-100"),("Embassy","5-7 days","$25-80","Express: 1-2 days","$50-100")],"health":"No mandatory vaccinations but Yellow Fever if from endemic area. Hepatitis A/B, Typhoid, Japanese Encephalitis recommended. Malaria prophylaxis for rural/highland areas. Medical facilities good in Hanoi/HCMC (Vinmec, FV Hospital). Limited elsewhere. Travel insurance recommended. No COVID-19 requirements.","extension":"Visa-free 45 days not extendable - must exit and re-enter. e-Visa 30 days: single entry, extendable once at immigration. Tourist visa extendable at immigration office or travel agent ($5-20). Maximum total stay varies. Overstay: $25/day fine. Significant overstay: deportation, 1-3 year entry ban.","refusal":"e-Visa rarely refused for eligible nationals. Common issues: passport name mismatch, photo problems, recent visit to restricted areas. No formal appeal. Can reapply online. VOA approval letters have near 100% success rate through authorized agents."},
}

def make_section(country, slug, d):
    """Generate HTML for 5 sections."""
    # 1. Visa Categories
    rows = ""
    for v in d["visas"]:
        rows += f'<tr><td><strong>{v[0]}</strong></td><td>{v[1]}</td><td>{v[2]}</td><td>{v[3]}</td></tr>\n'

    # 2. Processing
    proc_rows = ""
    for p in d["proc"]:
        proc_rows += f'<tr><td><strong>{p[0]}</strong></td><td>{p[1]}</td><td>{p[2]}</td><td>{p[3]}</td><td>{p[4]}</td></tr>\n'

    html = f'''
<div class="row mb-5">
<div class="col-md-12">
<h2 id="all-visas" style="font-size:22px;color:#1d2d50;border-bottom:3px solid #f15d30;padding-bottom:10px;margin-bottom:20px;">&#128203; Complete Visa Categories for {country}</h2>
<p>{country} offers several visa and permit categories depending on your purpose of travel, intended length of stay, and nationality. Below is a comprehensive overview of the main visa types available.</p>
<div class="table-responsive">
<table class="table table-bordered table-sm">
<thead><tr class="table-dark"><th>Visa Type</th><th>Duration</th><th>Fee (approx.)</th><th>Key Requirements</th></tr></thead>
<tbody>
{rows}</tbody>
</table></div>
<p><em>Fees and requirements may vary by nationality. Always verify at the official immigration authority.</em></p>
</div></div>

<div class="row mb-5">
<div class="col-md-12">
<h2 id="processing" style="font-size:22px;color:#1d2d50;border-bottom:3px solid #f15d30;padding-bottom:10px;margin-bottom:20px;">&#9200; Processing Times &amp; Fees for {country} Visas</h2>
<p>Processing times vary by visa type, nationality, and time of year. Apply well in advance of travel.</p>
<div class="table-responsive">
<table class="table table-bordered table-sm">
<thead><tr class="table-dark"><th>Visa Type</th><th>Standard Processing</th><th>Standard Fee</th><th>Expedited</th><th>Expedited Fee</th></tr></thead>
<tbody>
{proc_rows}</tbody>
</table></div>
</div></div>

<div class="row mb-5">
<div class="col-md-12">
<h2 id="health-requirements" style="font-size:22px;color:#1d2d50;border-bottom:3px solid #f15d30;padding-bottom:10px;margin-bottom:20px;">&#127973; Health &amp; Entry Requirements for {country}</h2>
<p>{d["health"]}</p>
</div></div>

<div class="row mb-5">
<div class="col-md-12">
<h2 id="extension" style="font-size:22px;color:#1d2d50;border-bottom:3px solid #f15d30;padding-bottom:10px;margin-bottom:20px;">&#128337; Visa Extension &amp; Overstay Rules in {country}</h2>
<p>{d["extension"]}</p>
</div></div>

<div class="row mb-5">
<div class="col-md-12">
<h2 id="refusal" style="font-size:22px;color:#1d2d50;border-bottom:3px solid #f15d30;padding-bottom:10px;margin-bottom:20px;">&#10060; Visa Refusal &amp; Appeals for {country}</h2>
<p>{d["refusal"]}</p>
</div></div>
'''
    return html


def main():
    enriched = 0
    skipped = 0

    for slug, d in DATA.items():
        fp = os.path.join(BASE, f"visa-{slug}.html")
        if not os.path.isfile(fp):
            print(f"  SKIP (not found): visa-{slug}.html")
            skipped += 1
            continue

        with open(fp, encoding="utf-8", errors="ignore") as f:
            html = f.read()

        if 'id="all-visas"' in html:
            print(f"  SKIP (already enriched): visa-{slug}.html")
            skipped += 1
            continue

        country = slug.replace("-", " ").title()
        if slug == "usa": country = "the United States"
        elif slug == "uae": country = "the UAE"
        elif slug == "united-kingdom": country = "the United Kingdom"
        elif slug == "south-korea": country = "South Korea"
        elif slug == "saudi-arabia": country = "Saudi Arabia"
        elif slug == "new-zealand": country = "New Zealand"
        elif slug == "sri-lanka": country = "Sri Lanka"
        elif slug == "costa-rica": country = "Costa Rica"

        sections = make_section(country, slug, d)

        # Insert before E-E-A-T section or footer
        inserted = False
        for marker in ['<!-- E-E-A-T', '<div class="eeat-section', '<div style="background:#f0f4ff']:
            if marker in html:
                html = html.replace(marker, sections + "\n" + marker, 1)
                inserted = True
                break

        if not inserted:
            html = html.replace('<footer', sections + "\n<footer", 1)
            inserted = True

        with open(fp, "w", encoding="utf-8") as f:
            f.write(html)
        enriched += 1
        print(f"  OK: visa-{slug}.html")

    print(f"\nDone: {enriched} enriched, {skipped} skipped.")


if __name__ == "__main__":
    main()
