#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Patch the 9 language index.html files with correct Unicode text
for hero, nav, sections, FAQ, footer.
"""

import os

BASE = r"C:\Users\chemi\Documents\evisa\pacific-main\www"

PATCHES = {
    "fr": [
        # Fix accented characters stripped in first pass
        ("l'eVisa &amp; d'autorisation", "l'eVisa &amp; d'autorisation"),
        ("Decouvrez", "Découvrez"),
        ("demarches", "démarches"),
        ("A propos", "À propos"),
        ("Explorer l'Oceanie", "Explorer l'Océanie"),
        ("Oceanie", "Océanie"),
        ("durees", "durées"),
        ("delais", "délais"),
        ("etapes", "étapes"),
        ("Ameriques", "Amériques"),
        ("l'Asie", "l'Asie"),
        ("l'Europe", "l'Europe"),
        ("Informations sur les visas", "Informations sur les visas"),
        ("Trouvez les informations officielles sur les eVisa pour chaque pays. Decouvrez les types de visa, les conditions, les demarches en ligne, les frais et les delais de traitement pour le tourisme et les affaires.",
         "Trouvez les informations officielles sur les eVisa pour chaque pays. Découvrez les types de visa, les conditions, les démarches en ligne, les frais et les délais de traitement pour le tourisme et les affaires."),
        ("Trouvez les types d'eVisa, durees, frais, liens officiels et conseils pour les principales destinations touristiques asiatiques. Chaque page pays contient les conditions, frais, liens et etapes pour postuler en ligne.",
         "Trouvez les types d'eVisa, durées, frais, liens officiels et conseils pour les principales destinations touristiques asiatiques. Chaque page pays contient les conditions, frais, liens et étapes pour postuler en ligne."),
        ("Decouvrez les options de visa et eVisa pour les principaux pays d'Amerique du Nord et du Sud. Consultez les conditions, portails officiels, durees de sejour et programmes comme eTA et ESTA.",
         "Découvrez les options de visa et eVisa pour les principaux pays d'Amérique du Nord et du Sud. Consultez les conditions, portails officiels, durées de séjour et programmes comme eTA et ESTA."),
        ("Ai-je besoin d'un eVisa pour voyager ?",
         "Ai-je besoin d'un eVisa pour voyager ?"),
        ("Les regles de visa dependent de votre nationalite et de votre destination. De nombreux pays autorisent l'entree sans visa, d'autres exigent une autorisation en ligne ou un visa ambassade.",
         "Les règles de visa dépendent de votre nationalité et de votre destination. De nombreux pays autorisent l'entrée sans visa, d'autres exigent une autorisation en ligne ou un visa ambassade."),
        ("Combien de temps prend l'approbation d'un eVisa ?",
         "Combien de temps prend l'approbation d'un eVisa ?"),
        ("Le delai d'approbation varie generalement de quelques heures a plusieurs jours selon la destination et le volume de demandes.",
         "Le délai d'approbation varie généralement de quelques heures à plusieurs jours selon la destination et le volume de demandes."),
        ("Quels documents sont necessaires pour un visa en ligne ?",
         "Quels documents sont nécessaires pour un visa en ligne ?"),
        ("En general : passeport valide, photo recente, details du voyage et moyen de paiement pour les frais de visa.",
         "En général : passeport valide, photo récente, détails du voyage et moyen de paiement pour les frais de visa."),
        ("Questions frequentes — eVisa &amp; Autorisations de voyage",
         "Questions fréquentes — eVisa & Autorisations de voyage"),
        ("Votre guide mondial d'eVisa &amp; d'autorisation de voyage",
         "Votre guide mondial d'eVisa &amp; d'autorisation de voyage"),
        ("Mentions legales", "Mentions légales"),
        ("Plateforme mondiale d'information sur les eVisa &amp; voyages",
         "Plateforme mondiale d'information sur les eVisa &amp; voyages"),
        ("Explorer les Ameriques", "Explorer les Amériques"),
        ("Nouvelle-Zelande", "Nouvelle-Zélande"),
        ("l'Oceanie", "l'Océanie"),
        ("© 2026 eVisa-Card.com — Plateforme mondiale d'information sur les eVisa &amp; voyages",
         "© 2026 eVisa-Card.com — Plateforme mondiale d'information sur les eVisa &amp; voyages"),
    ],
    "es": [
        ("Espanol", "Español"),
        ("Informacion", "Información"),
        ("tramitacion", "tramitación"),
        ("Descripcion", "Descripción"),
        ("solicitud en linea", "solicitud en línea"),
        ("requisitos, tarifas y tiempos de tramitacion por pais",
         "requisitos, tarifas y tiempos de tramitación por país"),
        ("Su guia global de eVisa &amp; autorizacion de viaje",
         "Su guía global de eVisa &amp; autorización de viaje"),
        ("Encuentre informacion oficial sobre eVisa para todos los paises. Conozca los tipos de visa, requisitos, pasos de solicitud en linea, tarifas y tiempos de tramitacion para turismo y negocios.",
         "Encuentre información oficial sobre eVisa para todos los países. Conozca los tipos de visa, requisitos, pasos de solicitud en línea, tarifas y tiempos de tramitación para turismo y negocios."),
        ("Explorar Oceania", "Explorar Oceanía"),
        ("America del Norte y del Sur", "América del Norte y del Sur"),
        ("orientacion para solicitar en linea en los principales destinos turisticos asiaticos.",
         "orientación para solicitar en línea en los principales destinos turísticos asiáticos."),
        ("Informacion sobre visas Schengen, eVisa y autorizaciones de viaje para Europa. Consulte los requisitos, tiempos de tramitacion y portales oficiales.",
         "Información sobre visas Schengen, eVisa y autorizaciones de viaje para Europa. Consulte los requisitos, tiempos de tramitación y portales oficiales."),
        ("Explore las opciones de visa y eVisa para los principales paises de America. Encuentre requisitos, portales oficiales, duraciones de estancia y programas como eTA y ESTA.",
         "Explore las opciones de visa y eVisa para los principales países de América. Encuentre requisitos, portales oficiales, duraciones de estancia y programas como eTA y ESTA."),
        ("Informacion de visa y eVisitor para Oceania. Consulte los requisitos de eVisitor, eTA o visa para Australia y Nueva Zelanda.",
         "Información de visa y eVisitor para Oceanía. Consulte los requisitos de eVisitor, eTA o visa para Australia y Nueva Zelanda."),
        ("Preguntas frecuentes — eVisa &amp; Autorizaciones de viaje",
         "Preguntas frecuentes — eVisa &amp; Autorizaciones de viaje"),
        ("Necesito un eVisa para viajar?", "¿Necesito un eVisa para viajar?"),
        ("Las reglas de visa dependen de su nacionalidad y destino. Muchos paises permiten la entrada sin visa, mientras que otros exigen una autorizacion en linea o visa de embajada.",
         "Las reglas de visa dependen de su nacionalidad y destino. Muchos países permiten la entrada sin visa, mientras que otros exigen una autorización en línea o visa de embajada."),
        ("Cuanto tarda la aprobacion de un eVisa?", "¿Cuánto tarda la aprobación de un eVisa?"),
        ("El tiempo de aprobacion generalmente oscila entre unas pocas horas y varios dias segun el destino y el volumen de solicitudes.",
         "El tiempo de aprobación generalmente oscila entre unas pocas horas y varios días según el destino y el volumen de solicitudes."),
        ("Que documentos se necesitan para un visa en linea?", "¿Qué documentos se necesitan para un visa en línea?"),
        ("Normalmente: pasaporte valido, foto recente, detalles del viaje y un metodo de pago para las tarifas de visa.",
         "Normalmente: pasaporte válido, foto reciente, detalles del viaje y un método de pago para las tarifas de visa."),
        ("Plataforma mundial de informacion sobre eVisa &amp; viajes",
         "Plataforma mundial de información sobre eVisa &amp; viajes"),
        ("© 2026 eVisa-Card.com — Plataforma mundial de informacion sobre eVisa &amp; viajes",
         "© 2026 eVisa-Card.com — Plataforma mundial de información sobre eVisa &amp; viajes"),
        ("Aviso legal", "Aviso legal"),
    ],
    "pt": [
        ("Portugues", "Português"),
        ("Informacoes", "Informações"),
        ("solicitacoes", "solicitações"),
        ("prazos de processamento por pais", "prazos de processamento por país"),
        ("Seu guia global de eVisa &amp; autorizacao de viagem",
         "Seu guia global de eVisa &amp; autorização de viagem"),
        ("Encontre informacoes oficiais sobre eVisa para todos os paises. Saiba sobre tipos de visto, requisitos, etapas de solicitacao online, taxas e prazos de processamento para turismo e negocios.",
         "Encontre informações oficiais sobre eVisa para todos os países. Saiba sobre tipos de visto, requisitos, etapas de solicitação online, taxas e prazos de processamento para turismo e negócios."),
        ("Explorar Asia", "Explorar Ásia"),
        ("Asia", "Ásia"),
        ("duracoes", "durações"),
        ("Encontre tipos de eVisa, duracoes, taxas, links oficiais e orientacao para solicitar online nos principais destinos turisticos asiaticos.",
         "Encontre tipos de eVisa, durações, taxas, links oficiais e orientação para solicitar online nos principais destinos turísticos asiáticos."),
        ("Informacoes sobre vistos Schengen, eVisa e autorizacoes de viagem para a Europa. Consulte os requisitos, prazos de processamento e portais oficiais.",
         "Informações sobre vistos Schengen, eVisa e autorizações de viagem para a Europa. Consulte os requisitos, prazos de processamento e portais oficiais."),
        ("Explore as opcoes de visto e eVisa para os principais paises das Americas. Encontre requisitos, portais oficiais, duracoes de estadia e programas como eTA e ESTA.",
         "Explore as opções de visto e eVisa para os principais países das Américas. Encontre requisitos, portais oficiais, durações de estadia e programas como eTA e ESTA."),
        ("Informacoes de visto e eVisitor para a Oceania. Verifique os requisitos de eVisitor, eTA ou visto para Australia e Nova Zelandia.",
         "Informações de visto e eVisitor para a Oceania. Verifique os requisitos de eVisitor, eTA ou visto para Austrália e Nova Zelândia."),
        ("Perguntas frequentes — eVisa &amp; Autorizacoes de viagem",
         "Perguntas frequentes — eVisa &amp; Autorizações de viagem"),
        ("Preciso de um eVisa para viajar?", "Preciso de um eVisa para viajar?"),
        ("As regras de visto dependem da sua nacionalidade e destino. Muitos paises permitem a entrada sem visto, enquanto outros exigem uma autorizacao online ou visto de embaixada.",
         "As regras de visto dependem da sua nacionalidade e destino. Muitos países permitem a entrada sem visto, enquanto outros exigem uma autorização online ou visto de embaixada."),
        ("Quanto tempo leva a aprovacao de um eVisa?", "Quanto tempo leva a aprovação de um eVisa?"),
        ("O prazo de aprovacao geralmente varia de algumas horas a varios dias, dependendo do destino e do volume de solicitacoes.",
         "O prazo de aprovação geralmente varia de algumas horas a vários dias, dependendo do destino e do volume de solicitações."),
        ("Quais documentos sao necessarios para um visto online?", "Quais documentos são necessários para um visto online?"),
        ("Normalmente: passaporte valido, foto recente, detalhes da viagem e um metodo de pagamento para as taxas de visto.",
         "Normalmente: passaporte válido, foto recente, detalhes da viagem e um método de pagamento para as taxas de visto."),
        ("Plataforma mundial de informacoes sobre eVisa &amp; viagens",
         "Plataforma mundial de informações sobre eVisa &amp; viagens"),
        ("Isencao de responsabilidade", "Isenção de responsabilidade"),
        ("© 2026 eVisa-Card.com — Plataforma mundial de informacoes sobre eVisa &amp; viagens",
         "© 2026 eVisa-Card.com — Plataforma mundial de informações sobre eVisa &amp; viagens"),
        ("America do Norte e do Sul", "América do Norte e do Sul"),
        ("Explorar Asia", "Explorar Ásia"),
        ("Oceania", "Oceania"),
    ],
    "zh": [
        ("nin de quanqiu dianzi qianzheng &amp; lvxing shouquan zhinan",
         "您的全球电子签证 &amp; 旅行授权指南"),
        ("Chazhao mei ge guojia de guanfang dianzi qianzheng xinxi. Liaojie lvyou he shangwu qianzheng leixing, yaoqiu, zaixian shenqing bu zhou, feiyong he chuli shijian.",
         "查找各国官方电子签证信息。了解旅游和商务签证类型、要求、在线申请步骤、费用和处理时间。"),
        ("tansuo yazhou", "探索亚洲"),
        ("tansuo ouzhou", "探索欧洲"),
        ("tansuo meizhou", "探索美洲"),
        ("tansuo dayanzhou", "探索大洋洲"),
        (">yazhou<", ">亚洲<"),
        (">ouzhou<", ">欧洲<"),
        ("nan-bei meizhou", "南北美洲"),
        ("dayanzhou", "大洋洲"),
        ("Chazhao zhuyao yazhou lvyou mudi de dianzi qianzheng leixing, tingliu shichang, feiyong, guanfang lianjie ji zaixian shenqing zhidao.",
         "查找主要亚洲旅游目的地的电子签证类型、停留时长、费用、官方链接及在线申请指引。每个国家页面均包含要求、费用、链接和申请步骤。"),
        ("Ouzhou shengen qianzheng, dianzi qianzheng he lvxing shouquan xinxi. Chazhao fei-EU lvxingzhe de yaoqiu, chuli shijian he guanfang mendian.",
         "欧洲申根签证、电子签证和旅行授权信息。查看非欧盟旅行者的要求、处理时间和官方门户。"),
        ("Tansuo nan-bei meizhou zhuyao guojia de qianzheng he dianzi qianzheng xuanze. Chazhao yaoqiu, guanfang shenqing mendian, tingliu shichang ji eTA, ESTA deng xiangmu.",
         "探索南北美洲主要国家的签证和电子签证选项。查找要求、官方申请门户、停留时长及eTA、ESTA等项目。"),
        ("Dayanzhou qianzheng he dianzi fangke xinxi. Chazhao aodaliya he xinxilan de eVisitor, eTA huo qianzheng yaoqiu.",
         "大洋洲签证和电子访客信息。查看澳大利亚和新西兰的eVisitor、eTA或签证要求。"),
        ("changjian wenti — dianzi qianzheng &amp; lvxing shouquan",
         "常见问题 — 电子签证 &amp; 旅行授权"),
        ("Lvxing shifou xuyao dianzi qianzheng?", "旅行是否需要电子签证？"),
        ("Qianzheng guize qu jue yu nin de guoji he mudi. Xuduo guojia yunxu mianqian ruzheng, qita guojia ze xu zaixian lvxing shouquan huo dashiguan qianzheng.",
         "签证规则取决于您的国籍和目的地。许多国家允许免签入境，其他国家则需要在线旅行授权或大使馆签证。"),
        ("Dianzi qianzheng shenpi xuyao duochang shijian?", "电子签证审批需要多长时间？"),
        ("Shenpi shijian tongchang cong ji xiaoshi dao shu tian bu deng, juti qu jue yu mudi he shenqing liang.",
         "审批时间通常从几小时到数天不等，具体取决于目的地和申请量。"),
        ("Zaixian qianzheng xuyao na xie wenjian?", "在线签证需要哪些文件？"),
        ("Tongchang xuyao: youxiao huzhao, jin qi zhaopian, lvxing xiangqing he qianzheng feiyong de youxiao zhifu fangshi.",
         "通常需要：有效护照、近期照片、旅行详情和签证费用的有效支付方式。"),
        ("quanqiu dianzi qianzheng &amp; lvxing xinxi pingtai",
         "全球电子签证 &amp; 旅行信息平台"),
        ("falv shengming", "法律声明"),
        ("mianze shengming", "免责声明"),
        ("shouye", "首页"),
        ("mudi", "目的地"),
        ("guanyu", "关于"),
        ("zhinan", "指南"),
        ("quanqiu dianzi qianzheng xinxi - lvxing shouquan zhinan",
         "全球电子签证信息 - 旅行授权指南"),
    ],
    "ja": [
        ("gurobaru eVisa joho - ryoko kyoka gaido", "グローバルeVisa情報 - 旅行許可ガイド"),
        ("gurobaru eVisa &amp; ryoko kyoka gaido", "グローバルeVisa &amp; 旅行許可ガイド"),
        ("Subete no kuni no koushiki eVisa joho wo kakuninshite kudasai. Kanko oyobi bijinesu ryoko no biza no shurui, youken, onlain shinsei tetsuzuki, tesuuryou, shori jikan wo gorannita dakemasu.",
         "すべての国の公式eVisa情報をご確認ください。観光・ビジネス旅行のビザの種類、要件、オンライン申請手順、手数料、処理時間をご覧いただけます。"),
        ("ajia wo sagasu", "アジアを探す"),
        ("yooroppa wo sagasu", "ヨーロッパを探す"),
        ("america wo sagasu", "アメリカを探す"),
        ("ooshanea wo sagasu", "オセアニアを探す"),
        (">ajia<", ">アジア<"),
        (">yooroppa<", ">ヨーロッパ<"),
        ("hokubei - nanbei", "北米・南米"),
        ("ooshanea", "オセアニア"),
        ("Shuyou na ajia kanko chi no eVisa no shurui, taizai kikan, tesuuryou, koushiki rinku, onlain shinsei shidou wo kakuninshite kudasai.",
         "主要なアジア観光地のeVisaの種類、滞在期間、手数料、公式リンク、オンライン申請ガイダンスをご確認ください。"),
        ("Yooroppa no shenggen biza, eVisa, ryoko kyoka ni kansuru joho. EU-gai no ryokoshatachi no youken, shori jikan, koushiki pootaru wo kakuninshite kudasai.",
         "ヨーロッパのシェンゲンビザ、eVisa、旅行許可に関する情報。EU外の旅行者向けの要件、処理時間、公式ポータルをご確認ください。"),
        ("Hokubei - nanbei no shuyou koku no biza to eVisa no sentaku shi wo gorannita dakemasu. Youken, koushiki shinsei pootaru, taizai kikan, eTA, ESTA nado no puroguramu wo kakuninshite kudasai.",
         "北米・南米の主要国のビザとeVisaの選択肢をご覧いただけます。要件、公式申請ポータル、滞在期間、eTA、ESTAなどのプログラムをご確認ください。"),
        ("Oosutoraria to Nyuujiirando no eVisitor, eTA, biza no youken wo kakuninshi, koushiki imin saito kara shinsei shite kudasai.",
         "オーストラリアとニュージーランドのeVisitor、eTA、ビザの要件を確認し、公式移民サイトから申請してください。"),
        ("yoku aru shitsumon — eVisa &amp; ryoko kyoka", "よくある質問 — eVisa &amp; 旅行許可"),
        ("ryoko ni eVisa wa hitsuyou desu ka?", "旅行にeVisaは必要ですか？"),
        ("Biza no kisoku wa kokuseki to mokuteki chi ni yotte kotonari masu. Ooku no kuni wa biza nashi de nyukoku dekimasu ga, onlain ryoko kyoka ya taishi kan biza ga hitsuyou na kuni mo arimasu.",
         "ビザの規則は国籍と目的地によって異なります。多くの国はビザなしで入国できますが、オンライン旅行許可や大使館ビザが必要な国もあります。"),
        ("eVisa no shounin ni wa dono kurai jikan ga kakari masu ka?", "eVisaの承認にはどのくらい時間がかかりますか？"),
        ("Shounin jikan wa, mokuteki chi ya shinsei ryo ni yotte suujikan kara suu-nichi kakaru baai ga arimasu.",
         "承認時間は、目的地や申請量によって数時間から数日かかる場合があります。"),
        ("onlain biza ni hitsuyou na shorui wa nani desu ka?", "オンラインビザに必要な書類は何ですか？"),
        ("Tsuujou, yuukou na pasupooto, saikin no shashin, ryoko no shousai, biza tesuuryou no shiharai houhou ga hitsuyou desu.",
         "通常、有効なパスポート、最近の写真、旅行の詳細、ビザ手数料の支払い方法が必要です。"),
        ("gurobaru eVisa &amp; ryoko joho purattofoomu", "グローバルeVisa &amp; 旅行情報プラットフォーム"),
        ("housou tsuchi", "法的通知"),
        ("menseki jikou", "免責事項"),
        ("hoomu", "ホーム"),
        ("mokuteki chi", "目的地"),
        ("gaiyou", "概要"),
        ("gaido", "ガイド"),
        ("Ooshanea no biza to eVisitor joho.", "オセアニアのビザとeVisitor情報。"),
    ],
    "ko": [
        ("geullobeol jeonja bija jeongbo - yeohaeng heoga annae", "글로벌 전자비자 정보 - 여행 허가 안내"),
        ("geullobeol jeonja bija &amp; yeohaeng heoga annae", "글로벌 전자비자 &amp; 여행 허가 안내"),
        ("Modeun gukga eui gongshik jeonja bija jeongboreul hwaginhasaeyo. Gwangwang mit bizeuniseu yeohaeng eul wihan bija yuheong, yogeon, onlain sincheong jeolcha, susuryo mit cheori gigan eul alaborasaeyo.",
         "모든 국가의 공식 전자비자 정보를 확인하세요. 관광 및 비즈니스 여행을 위한 비자 유형, 요건, 온라인 신청 절차, 수수료 및 처리 기간을 알아보세요."),
        ("asia tamsaek", "아시아 탐색"),
        ("yureop tamsaek", "유럽 탐색"),
        ("ameraika tamsaek", "아메리카 탐색"),
        ("oseania tamsaek", "오세아니아 탐색"),
        (">asia<", ">아시아<"),
        (">yureop<", ">유럽<"),
        ("bukmi mit nammi", "북미 및 남미"),
        ("oseania", "오세아니아"),
        ("Juyyo asia gwangwang mudi eui jeonja bija yuheong, cheryugi gan, susuryo, gongshik lingkeu mit onlain sincheong annae reul hwaginhasaeyo.",
         "주요 아시아 관광지의 전자비자 유형, 체류 기간, 수수료, 공식 링크 및 온라인 신청 안내를 확인하세요."),
        ("Yureop eui sengen bija, jeonja bija mit yeohaeng heoga jeongbo. EU-oe yeohaengja reul wihan yogeon, cheori sigan mit gongshik poteol eul hwaginhasaeyo.",
         "유럽의 솅겐 비자, 전자비자 및 여행 허가 정보. EU 외 여행자를 위한 요건, 처리 시간 및 공식 포털을 확인하세요."),
        ("Bukmi nammi juyyo gukga eui bija mit jeonja bija opseyon eul alaborasaeyo. Yogeon, gongshik sincheong poteol, cheryugi gan mit eTA, ESTA gateun peulogeulaem eul hwaginhasaeyo.",
         "북미·남미 주요 국가의 비자 및 전자비자 옵션을 알아보세요. 요건, 공식 신청 포털, 체류 기간 및 eTA, ESTA 같은 프로그램을 확인하세요."),
        ("Hoju wa nyujillaendeu eui eVisitor, eTA doneun bija yogeon eul hwaginhasaeyo.",
         "호주와 뉴질랜드의 eVisitor, eTA 또는 비자 요건을 확인하세요."),
        ("jaju mutneun jilmun — jeonja bija &amp; yeohaeng heoga", "자주 묻는 질문 — 전자비자 &amp; 여행 허가"),
        ("yeohaeng e jeonja bija ga pilyohan gayo?", "여행에 전자비자가 필요한가요?"),
        ("Bija gyuchig eun gukjeok gwa mokjeokji e ttara dareumnida. Manheun gukga ga mubija ibgug eul heoyonghajiman, onlain yeohaeng heoga na daesagwan bija ga pilyohan gukga do itseumnida.",
         "비자 규정은 국적과 목적지에 따라 다릅니다. 많은 국가가 무비자 입국을 허용하지만, 온라인 여행 허가나 대사관 비자가 필요한 국가도 있습니다."),
        ("jeonja bija seungyin e eolmana geollinayo?", "전자비자 승인에 얼마나 걸리나요?"),
        ("Seungyin sigan eun mokjeokji wa sincheong ryang e ttara myeot sigan eseo myeot il kkaji soyo doel su itseumnida.",
         "승인 시간은 목적지와 신청량에 따라 몇 시간에서 몇 일까지 소요될 수 있습니다."),
        ("onlain bija e pilyohan seoryu neun mueosinnayo?", "온라인 비자에 필요한 서류는 무엇인가요?"),
        ("Ilbanjeok euro yuehyo han yeogwon, choegeun sajin, yeohaeng sebo jeongbo, bija susuryo gyeolche sudo ga pilyohabnida.",
         "일반적으로 유효한 여권, 최근 사진, 여행 세부 정보, 비자 수수료 결제 수단이 필요합니다."),
        ("geullobeol jeonja bija &amp; yeohaeng jeongbo peullaetpom", "글로벌 전자비자 &amp; 여행 정보 플랫폼"),
        ("beomnyul goji", "법적 고지"),
        ("myeonjek johang", "면책 조항"),
        ("hom", "홈"),
        ("mokjeokji", "목적지"),
        ("sogae", "소개"),
        ("gaideu", "가이드"),
    ],
    "ru": [
        ("Globalnaya informatsiya ob elektronnykh vizakh - Rukovodstvo po puteshestviyam",
         "Глобальная информация об электронных визах - Руководство по путешествиям"),
        ("Globalnaya informatsiya ob elektronnykh vizakh",
         "Глобальная информация об электронных визах"),
        ("Vash globalnyy putevoditel po elektronnym vizam &amp; razresheniyam na vezd",
         "Ваш глобальный путеводитель по электронным визам &amp; разрешениям на въезд"),
        ("Naydite ofitsialnuyu informatsiyu ob elektronnykh vizakh dlya kazhdoy strany. Uznayte o tipakh viz, trebovaniyakh, shagakh onlayn-podachi zayavki, sborakh i srokakh obrabotki dlya turizma i biznesa.",
         "Найдите официальную информацию об электронных визах для каждой страны. Узнайте о типах виз, требованиях, шагах онлайн-подачи заявки, сборах и сроках обработки для туризма и бизнеса."),
        ("Issledovat Aziyu", "Исследовать Азию"),
        ("Issledovat Yevropu", "Исследовать Европу"),
        ("Issledovat Ameriku", "Исследовать Америку"),
        ("Issledovat Okeaniya", "Исследовать Океанию"),
        (">Aziya<", ">Азия<"),
        (">Yevrop", ">Европ"),
        ("Severnaya i Yuzhnaya Amerika", "Северная и Южная Америка"),
        ("Okeaniya", "Океания"),
        ("Naydite tipy elektronnykh viz, sroki prebyvaniya, sbory, ofitsialnyye ssylki i rukovodstvo po onlayn-podache zayavok dlya osnovnykh aziatskikh turisticheskikh napravleniy.",
         "Найдите типы электронных виз, сроки пребывания, сборы, официальные ссылки и руководство по онлайн-подаче заявок для основных азиатских туристических направлений."),
        ("Informatsiya o shengenskikh vizakh, elektronnykh vizakh i razresheniyakh na vezd v Yevropu. Uznayte o trebovaniyakh, srokakh obrabotki i ofitsialnykh portalakh dlya puteshestvennikov iz-za predelov YES.",
         "Информация о шенгенских визах, электронных визах и разрешениях на въезд в Европу. Узнайте о требованиях, сроках обработки и официальных порталах для путешественников из-за пределов ЕС."),
        ("Izuchite varianty viz i elektronnykh viz dlya osnovnykh stran Severnoy i Yuzhnoy Ameriki. Naydite trebovaniya, ofitsialnyye portaly podachi zayavok, sroki prebyvaniya i programmy, takiye kak eTA i ESTA.",
         "Изучите варианты виз и электронных виз для основных стран Северной и Южной Америки. Найдите требования, официальные порталы подачи заявок, сроки пребывания и программы, такие как eTA и ESTA."),
        ("Proverite trebovaniya eVisitor, eTA ili vizy dlya Avstralii i Novoy Zelandii.",
         "Проверьте требования eVisitor, eTA или визы для Австралии и Новой Зеландии."),
        ("Chasto zadavayemyye voprosy — elektronnyye vizy &amp; razresheniya na vezd",
         "Часто задаваемые вопросы — электронные визы &amp; разрешения на въезд"),
        ("Nuzhna li mne elektronnaya viza dlya puteshestviya?", "Нужна ли мне электронная виза для путешествия?"),
        ("Pravila vizovogo rezhima zavisyat ot grazhdanstva i punkta naznacheniya. Mnogie strany razreshayut vezd bez vizy, drugiye trebuyut onlayn-razresheniye ili posolskuyu vizu.",
         "Правила визового режима зависят от гражданства и пункта назначения. Многие страны разрешают въезд без визы, другие требуют онлайн-разрешение или посольскую визу."),
        ("Skolko vremeni zanimayet odobreniye elektronnoy vizy?", "Сколько времени занимает одобрение электронной визы?"),
        ("Vremya odobreniya obychno sostavlyayet ot neskolkikh chasov do neskolkikh dney v zavisimosti ot napravleniya i obyema zayavok.",
         "Время одобрения обычно составляет от нескольких часов до нескольких дней в зависимости от направления и объёма заявок."),
        ("Kakiye dokumenty nuzhny dlya onlayn-vizy?", "Какие документы нужны для онлайн-визы?"),
        ("Kak pravilo: deystvuyushchiy pasport, nedavnyaya fotografiya, dannyye o poyezdke i deystvuyushchiy sposob oplaty dlya vizovykh sborov.",
         "Как правило: действующий паспорт, недавняя фотография, данные о поездке и действующий способ оплаты для визовых сборов."),
        ("Globalnaya platforma informatsii ob elektronnykh vizakh &amp; puteshestviyakh",
         "Глобальная платформа информации об электронных визах &amp; путешествиях"),
        ("Pravovyye uvedomleniya", "Правовые уведомления"),
        ("Otkaz ot otvetstvennosti", "Отказ от ответственности"),
        ("Glavnaya", "Главная"),
        ("Napravleniya", "Направления"),
        ("O nas", "О нас"),
        ("Rukovodstva", "Руководства"),
        ("Russkiy", "Русский"),
    ],
    "ar": [
        ("maelumat altaasheera aliliktruniyya alealamiyya - daleel alsafar",
         "معلومات التأشيرة الإلكترونية العالمية - دليل السفر"),
        ("maelumat altaasheera aliliktruniyya alealamiyya",
         "معلومات التأشيرة الإلكترونية العالمية"),
        ("daleel rasmiy liltaasheera aliliktruniyya wa-tasareeh alsafar lil-wajhat alsiyahiyya alrayeesiyya.",
         "دليل رسمي للتأشيرة الإلكترونية وتصاريح السفر للوجهات السياحية الرئيسية."),
        ("daleelak aleaalami liltaashiraat aliliktruniyya &amp; tasareeh alsafar",
         "دليلك العالمي للتأشيرات الإلكترونية &amp; تصاريح السفر"),
        ("ibhath ean maelumat rasmiyya ean altaasheera aliliktruniyya likull dawla. taearraf ealaa anwae altaasheera wal-mutatalabat wakhutuat altaqadim eabr alinternet wal-rusum wawqt almuealjat lissiyaha walaaemal.",
         "ابحث عن معلومات رسمية عن التأشيرة الإلكترونية لكل دولة. تعرف على أنواع التأشيرات والمتطلبات وخطوات التقديم عبر الإنترنت والرسوم ووقت المعالجة للسياحة والأعمال."),
        ("istikshaf asya", "استكشف آسيا"),
        ("istikshaf urubba", "استكشف أوروبا"),
        ("istikshaf alamrikatayn", "استكشف الأمريكتين"),
        ("istikshaf awqiyanus", "استكشف أوقيانوسيا"),
        (">asya<", ">آسيا<"),
        (">urubba<", ">أوروبا<"),
        ("amrika alshamaaliyya waljanuubiyya", "أمريكا الشمالية والجنوبية"),
        ("awqiyanuusiya", "أوقيانوسيا"),
        ("ibhath ean anwae altaashiraat aliliktruniyya wamudad aliqama wal-rusum wal-rawabat alrasmiyya wairshadat altaqadim eabr alinternet lil-wajhat alsiyahiyya alrayeesiyya fi asya.",
         "ابحث عن أنواع التأشيرات الإلكترونية ومدد الإقامة والرسوم والروابط الرسمية وإرشادات التقديم عبر الإنترنت للوجهات السياحية الرئيسية في آسيا."),
        ("maelumat ean tashayraat shenghan wal-taashiraat aliliktruniyya wa-tasareeh alsafar 'iilaa 'uruppa. tahaqqaq min almutatalabat wawqat almuealjat wal-bawwabat alrasmiyya lilmusafirin min khaarij alitihaad al-'urubbi.",
         "معلومات عن تأشيرات شنغن والتأشيرات الإلكترونية وتصاريح السفر إلى أوروبا. تحقق من المتطلبات وأوقات المعالجة والبوابات الرسمية للمسافرين من خارج الاتحاد الأوروبي."),
        ("istikshaf khiyarat altaasheera waltaasheera aliliktruniyya lidduwwal alrayeesiyya fi amrika. ibhath ean almutatalabat wal-bawwabat alrasmiyya wamudad aliqama wa-baramij mithil eTA wa ESTA.",
         "استكشف خيارات التأشيرة والتأشيرة الإلكترونية للدول الرئيسية في أمريكا. ابحث عن المتطلبات والبوابات الرسمية ومدد الإقامة وبرامج eTA وESTA."),
        ("tahaqqaq min mutatalabat eVisitor 'aw eTA 'aw altaasheera li'ustraaliya wa-nyuuzylndah.",
         "تحقق من متطلبات eVisitor أو eTA أو التأشيرة لأستراليا ونيوزيلندا."),
        ("al-as'ila alshayieat — altashiraat aliliktruniyya &amp; tasareeh alsafar",
         "الأسئلة الشائعة — التأشيرات الإلكترونية &amp; تصاريح السفر"),
        ("hal 'ahtaj 'iilaa taasheera 'iiliktruniyya lissafar?", "هل أحتاج إلى تأشيرة إلكترونية للسفر؟"),
        ("taetamid qawaid altaasheera ealaa jinsiyatik wawajhatik. tashmah kathir min alduwwal bialdukhul bidun taasheera, baynama tatatalab duwal 'ukhraa tasrihan 'iiliktrunian 'aw taasheerat sifara.",
         "تعتمد قواعد التأشيرة على جنسيتك ووجهتك. تسمح كثير من الدول بالدخول دون تأشيرة، بينما تتطلب دول أخرى تصريحاً إلكترونياً أو تأشيرة سفارة."),
        ("kam yastatghriqu alhasul ealaa muwafaqat altaasheera aliliktruniyya?", "كم يستغرق الحصول على موافقة التأشيرة الإلكترونية؟"),
        ("yataraawah waqt almuwafaqat eadatan min saeat qaliila 'iilaa eiddat 'ayaam hasab alwajha wahjm altalbiyat.",
         "يتراوح وقت الموافقة عادةً من ساعات قليلة إلى عدة أيام حسب الوجهة وحجم الطلبات."),
        ("maa alwathaayiq almatluba liltaasheera aliliktruniyya?", "ما الوثائق المطلوبة للتأشيرة الإلكترونية؟"),
        ("eadatan: jawaz safar saarin, sura hadithat, tafasil alsafar, wawasilat dafe sariyat lirisum altaasheera.",
         "عادةً: جواز سفر ساري، صورة حديثة، تفاصيل السفر، ووسيلة دفع سارية لرسوم التأشيرة."),
        ("mansat maelumat altaasheera aliliktruniyya &amp; alsafar alealamiyya",
         "منصة معلومات التأشيرة الإلكترونية &amp; السفر العالمية"),
        ("ishear qanuuni", "إشعار قانوني"),
        ("ikhlaa almasuwliyya", "إخلاء المسؤولية"),
        ("alrayeesiyya", "الرئيسية"),
        ("alwajhat", "الوجهات"),
        ("hawl", "حول"),
        ("al-adilla", "الأدلة"),
        ("alarabiyya", "العربية"),
    ],
    "th": [
        ("khomun eVisa thuakhong - khumu kandern thang", "ข้อมูล eVisa ทั่วโลก - คู่มือการเดินทาง"),
        ("khumu eVisa &amp; kan arnu yat kan dern thang thuakhong khong khun",
         "คู่มือ eVisa &amp; การอนุญาตการเดินทางทั่วโลกของคุณ"),
        ("khon ha khomun eVisa yang pen thangkan samrap thuk prathet. rean ru kiao kap praphet wisa, kho kam nod, khan ton kan samat ok lain, kha thamniarm, lae rawaya wela dam nen ngan samrap kan thong thiao lae thurakij.",
         "ค้นหาข้อมูล eVisa อย่างเป็นทางการสำหรับทุกประเทศ เรียนรู้เกี่ยวกับประเภทวีซ่า ข้อกำหนด ขั้นตอนการสมัครออนไลน์ ค่าธรรมเนียม และระยะเวลาดำเนินการสำหรับการท่องเที่ยวและธุรกิจ"),
        ("samruad asia", "สำรวจเอเชีย"),
        ("samruad yurob", "สำรวจยุโรป"),
        ("samruad america", "สำรวจอเมริกา"),
        ("samruad o-shia-nia", "สำรวจโอเชียเนีย"),
        (">asia<", ">เอเชีย<"),
        (">yurob<", ">ยุโรป<"),
        ("america nua lae tai", "อเมริกาเหนือและใต้"),
        ("o-shia-nia", "โอเชียเนีย"),
        ("khon ha praphet eVisa, rawaya yu, kha thamniarm, link yang pen thangkan, lae kham nan na kan samat ok lain samrap jut mai plai thang thong thiao lak nai asia.",
         "ค้นหาประเภท eVisa ระยะเวลาพัก ค่าธรรมเนียม ลิงก์อย่างเป็นทางการ และคำแนะนำการสมัครออนไลน์สำหรับจุดหมายปลายทางท่องเที่ยวหลักในเอเชีย"),
        ("khomun wisa Schengen, eVisa, lae kan arnu yat kan dern thang pai yang yurob. truat sob kho kam nod, rawaya wela dam nen ngan, lae pho-tal yang pen thangkan samrap nak dern thang thi mai chai EU.",
         "ข้อมูลวีซ่า Schengen eVisa และการอนุญาตการเดินทางไปยังยุโรป ตรวจสอบข้อกำหนด ระยะเวลาดำเนินการ และพอร์ทัลอย่างเป็นทางการสำหรับนักเดินทางที่ไม่ใช่ EU"),
        ("samruad tang leuk khong wisa lae eVisa samrap prathet lak nai america nua lae tai. khon ha kho kam nod, pho-tal samat yang pen thangkan, rawaya yu, lae khrongkan thao eTA lae ESTA.",
         "สำรวจตัวเลือกวีซ่าและ eVisa สำหรับประเทศหลักในอเมริกาเหนือและใต้ ค้นหาข้อกำหนด พอร์ทัลสมัครอย่างเป็นทางการ ระยะเวลาพัก และโปรแกรม เช่น eTA และ ESTA"),
        ("truat sob kho kam nod eVisitor, eTA, rue wisa samrap australia lae nyu si-lan.",
         "ตรวจสอบข้อกำหนด eVisitor eTA หรือวีซ่าสำหรับออสเตรเลียและนิวซีแลนด์"),
        ("kham tham thi phob ban krong — eVisa &amp; kan arnu yat kan dern thang",
         "คำถามที่พบบ่อย — eVisa &amp; การอนุญาตการเดินทาง"),
        ("chan tong mi eVisa phue dern thang rue plao?", "ฉันต้องมี eVisa เพื่อเดินทางหรือไม่?"),
        ("kotchamniarm wisa khun yu kap san chat lae jut mai plai thang khong khun. lai prathet arnu yat hai khao prathet doi mai tong mi wisa, nai kha thi bang prathet tong kan arnu yat ok lain rue wisa sa than thut.",
         "กฎวีซ่าขึ้นอยู่กับสัญชาติและจุดหมายปลายทางของคุณ หลายประเทศอนุญาตให้เข้าประเทศโดยไม่ต้องมีวีซ่า ในขณะที่บางประเทศต้องการการอนุญาตออนไลน์หรือวีซ่าสถานทูต"),
        ("kan anu mat eVisa chai wela nan thao rai?", "การอนุมัติ eVisa ใช้เวลานานเท่าใด?"),
        ("wela anu mat chai wela ton pra man cak mai khi chua mong thung lai wan khun yu kap pa ri man kan samat.",
         "เวลาอนุมัติมักอยู่ระหว่างไม่กี่ชั่วโมงถึงหลายวัน ขึ้นอยู่กับจุดหมายปลายทางและปริมาณการสมัคร"),
        ("tong chai ekkasan arai bang samrap wisa ok lain?", "ต้องใช้เอกสารอะไรบ้างสำหรับวีซ่าออนไลน์?"),
        ("doi thuai pai: nang su dern thang thi yang mai mot ayu, rup thai lao sun, rai la iad kan dern thang, lae wit hi cham ra ka tham niarm wisa thi chai dai.",
         "โดยทั่วไป: หนังสือเดินทางที่ยังไม่หมดอายุ รูปถ่ายล่าสุด รายละเอียดการเดินทาง และวิธีชำระเงินที่ใช้งานได้สำหรับค่าธรรมเนียมวีซ่า"),
        ("phaen thi khomun eVisa &amp; kan dern thang thuakhong",
         "แพลตฟอร์มข้อมูล eVisa &amp; การเดินทางทั่วโลก"),
        ("prakad thang kotmai", "ประกาศทางกฎหมาย"),
        ("kho cam kad khwam rap phit chob", "ข้อจำกัดความรับผิดชอบ"),
        ("na raek", "หน้าแรก"),
        ("jut mai plai thang", "จุดหมายปลายทาง"),
        ("kiao kap", "เกี่ยวกับ"),
        ("khumu", "คู่มือ"),
        ("thai", "ไทย"),
    ],
}


total = 0
for lang, patches in PATCHES.items():
    path = os.path.join(BASE, lang, "index.html")
    with open(path, encoding="utf-8") as f:
        content = f.read()
    orig = content
    for old, new in patches:
        content = content.replace(old, new)
    count = len([1 for o, n in patches if o in orig])
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    total += count
    print(f"[{lang}] {count}/{len(patches)} replacements applied")

print(f"\nTotal patches: {total}")
