#!/usr/bin/env python3
import os

BASE = r"C:\Users\chemi\Documents\evisa\pacific-main\www\zh"

# Replacements are ordered from longest/most-specific to shortest/most-generic
# to avoid partial replacements clobbering later ones.
REPLACEMENTS = [
    # ── PAGE TITLES ────────────────────────────────────────────────────────────
    ("Expat Guide Thailand 2026 — How to Live in Thailand | eVisa-Card.com",
     "泰国侨民指南2026 — 如何在泰国生活 | eVisa-Card.com"),
    ("Expat Guide Japan 2026 — How to Live in Japan | eVisa-Card.com",
     "日本侨民指南2026 — 如何在日本生活 | eVisa-Card.com"),
    ("Expat Guide Vietnam 2026 — How to Live in Vietnam | eVisa-Card.com",
     "越南侨民指南2026 — 如何在越南生活 | eVisa-Card.com"),
    ("Expat Guide Malaysia 2026 — How to Live in Malaysia | eVisa-Card.com",
     "马来西亚侨民指南2026 — 如何在马来西亚生活 | eVisa-Card.com"),
    ("Expat Guide Cambodia 2026 — How to Live in Cambodia | eVisa-Card.com",
     "柬埔寨侨民指南2026 — 如何在柬埔寨生活 | eVisa-Card.com"),
    ("Expat Guide Laos 2026 — How to Live in Laos | eVisa-Card.com",
     "老挝侨民指南2026 — 如何在老挝生活 | eVisa-Card.com"),
    ("Complete Expat Guide Georgia 2026 — Live & Work in Georgia (Caucasus)",
     "格鲁吉亚完整侨民指南2026 — 在格鲁吉亚生活与工作"),
    ("Expat Guide Greece 2026 — How to Live in Greece | eVisa-Card.com",
     "希腊侨民指南2026 — 如何在希腊生活 | eVisa-Card.com"),
    ("Expat Guide Spain 2026 — How to Live in Spain | eVisa-Card.com",
     "西班牙侨民指南2026 — 如何在西班牙生活 | eVisa-Card.com"),
    ("Expat Guide Portugal 2026 — How to Live in Portugal | eVisa-Card.com",
     "葡萄牙侨民指南2026 — 如何在葡萄牙生活 | eVisa-Card.com"),
    ("Expat Guide Mexico 2026 — How to Live in Mexico | eVisa-Card.com",
     "墨西哥侨民指南2026 — 如何在墨西哥生活 | eVisa-Card.com"),
    ("Expat Guide Colombia 2026 — How to Live in Colombia | eVisa-Card.com",
     "哥伦比亚侨民指南2026 — 如何在哥伦比亚生活 | eVisa-Card.com"),
    ("Expat Guide Costa Rica 2026 — How to Live in Costa Rica | eVisa-Card.com",
     "哥斯达黎加侨民指南2026 — 如何在哥斯达黎加生活 | eVisa-Card.com"),
    ("Expat Guide Panama 2026 — How to Live in Panama | eVisa-Card.com",
     "巴拿马侨民指南2026 — 如何在巴拿马生活 | eVisa-Card.com"),
    ("Expat Guide Paraguay 2026 — How to Live in Paraguay | eVisa-Card.com",
     "巴拉圭侨民指南2026 — 如何在巴拉圭生活 | eVisa-Card.com"),
    ("Expat Guide UAE 2026 — How to Live in UAE | eVisa-Card.com",
     "阿联酋侨民指南2026 — 如何在阿联酋生活 | eVisa-Card.com"),

    # ── META DESCRIPTIONS ──────────────────────────────────────────────────────
    ('content="Complete expat guide to living in Thailand 2026. Visa options, step-by-step residency process, housing, banking, healthcare and cost of living."',
     'content="泰国生活完整侨民指南2026。签证选项、分步居留程序、住房、银行、医疗保健和生活成本。"'),
    ('content="Complete expat guide Japan 2026. Highly skilled worker visa, digital nomad visa, step-by-step residency, housing in Tokyo &amp; Osaka, banking, healthcare."',
     'content="日本完整侨民指南2026。高技能工作者签证、数字游民签证、分步居留、东京大阪住房、银行业务、医疗保健。"'),
    ('content="Complete expat guide Vietnam 2026. E-Visa, TRC, housing in Hanoi &amp; Ho Chi Minh City, banking, healthcare, cost of living."',
     'content="越南完整侨民指南2026。电子签证、临时居留证、河内及胡志明市住房、银行业务、医疗保健、生活成本。"'),
    ('content="Complete expat guide Spain 2026. Non-Lucrative Visa, Digital Nomad Visa, NIE, step-by-step residency, housing, banking, healthcare."',
     'content="西班牙完整侨民指南2026。非营利签证、数字游民签证、外国人身份证、分步居留、住房、银行业务、医疗保健。"'),
    ('content="Complete guide to living in Georgia (Caucasus) as an expat in 2026. Visa-free 365 days, residency by investment, flat 20% tax, healthcare, bank accounts and property for foreigners."',
     'content="2026年在格鲁吉亚（高加索）作为侨民生活的完整指南。365天免签证、投资居留、20%统一税、医疗保健、外国人银行账户和房产。"'),

    # ── HERO H1 TITLES ─────────────────────────────────────────────────────────
    ("Expat Guide: Living in Thailand 2026",
     "侨民指南：2026年在泰国生活"),
    ("Expat Guide: Living in Japan 2026",
     "侨民指南：2026年在日本生活"),
    ("Expat Guide: Living in Vietnam 2026",
     "侨民指南：2026年在越南生活"),
    ("Expat Guide: Living in Malaysia 2026",
     "侨民指南：2026年在马来西亚生活"),
    ("Expat Guide: Living in Cambodia 2026",
     "侨民指南：2026年在柬埔寨生活"),
    ("Expat Guide: Living in Laos 2026",
     "侨民指南：2026年在老挝生活"),
    ("Expat Guide: Living in Georgia 2026",
     "侨民指南：2026年在格鲁吉亚生活"),
    ("Expat Guide: Living in Greece 2026",
     "侨民指南：2026年在希腊生活"),
    ("Expat Guide: Living in Spain 2026",
     "侨民指南：2026年在西班牙生活"),
    ("Expat Guide: Living in Portugal 2026",
     "侨民指南：2026年在葡萄牙生活"),
    ("Expat Guide: Living in Mexico 2026",
     "侨民指南：2026年在墨西哥生活"),
    ("Expat Guide: Living in Colombia 2026",
     "侨民指南：2026年在哥伦比亚生活"),
    ("Expat Guide: Living in Colombia",
     "侨民指南：在哥伦比亚生活"),
    ("Expat Guide: Living in Costa Rica 2026",
     "侨民指南：2026年在哥斯达黎加生活"),
    ("Expat Guide: Living in Panama 2026",
     "侨民指南：2026年在巴拿马生活"),
    ("Expat Guide: Living in Paraguay 2026",
     "侨民指南：2026年在巴拉圭生活"),
    ("Expat Guide: Living in UAE 2026",
     "侨民指南：2026年在阿联酋生活"),

    # ── BREADCRUMB COUNTRY NAMES ───────────────────────────────────────────────
    ("Expat Guide Thailand <i class=\"fa fa-chevron-right\"></i>",
     "泰国侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Japan <i class=\"fa fa-chevron-right\"></i>",
     "日本侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Vietnam <i class=\"fa fa-chevron-right\"></i>",
     "越南侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Malaysia <i class=\"fa fa-chevron-right\"></i>",
     "马来西亚侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Cambodia <i class=\"fa fa-chevron-right\"></i>",
     "柬埔寨侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Laos <i class=\"fa fa-chevron-right\"></i>",
     "老挝侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Greece <i class=\"fa fa-chevron-right\"></i>",
     "希腊侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Spain <i class=\"fa fa-chevron-right\"></i>",
     "西班牙侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Portugal <i class=\"fa fa-chevron-right\"></i>",
     "葡萄牙侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Mexico <i class=\"fa fa-chevron-right\"></i>",
     "墨西哥侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Costa Rica <i class=\"fa fa-chevron-right\"></i>",
     "哥斯达黎加侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Panama <i class=\"fa fa-chevron-right\"></i>",
     "巴拿马侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide Paraguay <i class=\"fa fa-chevron-right\"></i>",
     "巴拉圭侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    ("Expat Guide UAE <i class=\"fa fa-chevron-right\"></i>",
     "阿联酋侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    # Georgia breadcrumb uses a different pattern (span>Georgia)
    (">Expat Guides <i class=\"fa fa-chevron-right\"></i>",
     ">侨民指南 <i class=\"fa fa-chevron-right\"></i>"),
    # Colombia breadcrumb (no chevron after)
    ("Expat Guide: Living in Colombia",
     "侨民指南：在哥伦比亚生活"),

    # ── BREADCRUMB "Home" → "首页" ──────────────────────────────────────────────
    (">Home <i class=\"fa fa-chevron-right\"></i>",
     ">首页 <i class=\"fa fa-chevron-right\"></i>"),

    # ── JSON-LD schema name field (in script tags) ─────────────────────────────
    ('"name": "Expat Guide: Living in Thailand 2026"',
     '"name": "侨民指南：2026年在泰国生活"'),
    ('"name": "Expat Guide: Living in Japan 2026"',
     '"name": "侨民指南：2026年在日本生活"'),
    ('"name": "Expat Guide: Living in Vietnam 2026"',
     '"name": "侨民指南：2026年在越南生活"'),
    ('"name": "Expat Guide: Living in Spain 2026"',
     '"name": "侨民指南：2026年在西班牙生活"'),
    ('"name": "Expat Guide: Living in Georgia 2026"',
     '"name": "侨民指南：2026年在格鲁吉亚生活"'),

    # ── "AT A GLANCE" SECTION HEADERS ─────────────────────────────────────────
    ("Thailand at a Glance",  "泰国概况"),
    ("Japan at a Glance",     "日本概况"),
    ("Vietnam at a Glance",   "越南概况"),
    ("Malaysia at a Glance",  "马来西亚概况"),
    ("Cambodia at a Glance",  "柬埔寨概况"),
    ("Laos at a Glance",      "老挝概况"),
    ("Georgia at a Glance",   "格鲁吉亚概况"),
    ("Greece at a Glance",    "希腊概况"),
    ("Spain at a Glance",     "西班牙概况"),
    ("Portugal at a Glance",  "葡萄牙概况"),
    ("Mexico at a Glance",    "墨西哥概况"),
    ("Colombia at a Glance",  "哥伦比亚概况"),
    ("Costa Rica at a Glance","哥斯达黎加概况"),
    ("Panama at a Glance",    "巴拿马概况"),
    ("Paraguay at a Glance",  "巴拉圭概况"),
    ("UAE at a Glance",       "阿联酋概况"),

    # ── INTRO PARAGRAPHS (Thailand) ────────────────────────────────────────────
    ("Thailand is one of the world's top expat destinations, attracting retirees, digital nomads and families with its warm climate, affordable cost of living, world-class cuisine and welcoming culture. This guide walks you through everything you need to know to relocate to Thailand in 2026.",
     "泰国是全球最受欢迎的侨民目的地之一，以温暖的气候、实惠的生活成本、世界级美食和热情好客的文化吸引退休人员、数字游民和家庭。本指南将引导您了解2026年移居泰国所需的一切信息。"),

    # ── INTRO PARAGRAPHS (Japan) ───────────────────────────────────────────────
    ("Japan offers a unique expat experience: ultra-safe, technologically advanced, culturally rich and with excellent public services. Tokyo, Osaka, Kyoto and Fukuoka attract expats with high quality of life, world-class healthcare and efficient public transport. Japan introduced a digital nomad visa in 2024.",
     "日本为侨民提供独特的体验：极度安全、技术先进、文化丰富，拥有优质的公共服务。东京、大阪、京都和福冈以高品质生活、世界级医疗保健和高效公共交通吸引侨民。日本于2024年推出了数字游民签证。"),

    # ── INTRO PARAGRAPHS (Vietnam) ─────────────────────────────────────────────
    ("Vietnam has emerged as one of Southeast Asia's top expat and digital nomad destinations, with ultra-low cost of living, vibrant cities, and stunning landscapes. Hanoi, Ho Chi Minh City, Da Nang and Hoi An offer exceptional quality of life at a fraction of Western costs.",
     "越南已成为东南亚顶级侨民和数字游民目的地之一，生活成本极低、城市充满活力、风景秀丽。河内、胡志明市、岘港和会安以远低于西方的价格提供卓越的生活品质。"),

    # ── INTRO PARAGRAPHS (Malaysia) ────────────────────────────────────────────
    ("Malaysia combines tropical living, modern infrastructure, multicultural society, and one of Southeast Asia's most affordable costs of living. Kuala Lumpur, Penang, and Johor Bahru are popular expat hubs. The MM2H (Malaysia My Second Home) program offers long-term residency for qualified applicants.",
     "马来西亚融合了热带生活、现代基础设施、多元文化社会，以及东南亚最实惠的生活成本之一。吉隆坡、槟城和新山是热门侨民聚居地。MM2H（马来西亚我的第二家园）计划为合格申请人提供长期居留。"),

    # ── INTRO PARAGRAPHS (Spain) ───────────────────────────────────────────────
    ("Spain remains one of the world's top expat destinations thanks to its Mediterranean climate, vibrant culture, excellent healthcare, high quality of life and relatively affordable cost of living outside major cities. Whether you're retiring, working remotely or starting a business, Spain has a path for you.",
     "西班牙凭借地中海气候、充满活力的文化、卓越的医疗保健、高品质生活以及大城市以外相对实惠的生活成本，依然是全球顶级侨民目的地之一。无论您是退休、远程工作还是创业，西班牙都有适合您的途径。"),

    # ── INTRO PARAGRAPHS (Georgia) ─────────────────────────────────────────────
    ("Georgia (the Caucasus country) has emerged as one of the most popular destinations for digital nomads, entrepreneurs and expats worldwide. The reasons: 365-day visa-free entry for 95+ nationalities, a flat 20% income tax (1% for small businesses), ultra-low cost of living, fast internet and a young, cosmopolitan capital in Tbilisi.",
     "格鲁吉亚（高加索国家）已成为全球数字游民、企业家和侨民最受欢迎的目的地之一。原因在于：95个以上国籍可享365天免签证入境、统一20%所得税（小企业1%）、极低生活成本、快速互联网以及充满活力的年轻都市首都第比利斯。"),

    # ── INTRO PARAGRAPHS (Colombia) ────────────────────────────────────────────
    ("Colombia has transformed into one of Latin America's top expat destinations. With a thriving digital nomad scene in Medellín, stunning Caribbean coast, and one of the most affordable costs of living in the region, Colombia offers an outstanding quality of life for internationals.",
     "哥伦比亚已转变为拉丁美洲顶级侨民目的地之一。凭借麦德林蓬勃发展的数字游民场景、迷人的加勒比海岸以及该地区最实惠的生活成本之一，哥伦比亚为国际人士提供卓越的生活品质。"),

    # ── LAST UPDATED LINE ──────────────────────────────────────────────────────
    ("Last updated: March 2026 — <em>编辑团队, eVisa-Card.com</em>",
     "最后更新：2026年3月 — <em>编辑团队, eVisa-Card.com</em>"),
    ("Last updated: March 2026 — 编辑团队, eVisa-Card.com",
     "最后更新：2026年3月 — 编辑团队, eVisa-Card.com"),
    ("Updated March 2026",  "更新于2026年3月"),
    ("Updated March 2026",  "更新于2026年3月"),

    # ── SECTION HEADERS ────────────────────────────────────────────────────────
    ("Visa &amp; Residency Options",    "签证与居留选项"),
    ("Visa & Residency Options",        "签证与居留选项"),
    ("🛂 Visa & Residency Options",     "🛂 签证与居留选项"),
    ("Step-by-Step: How to Move to Thailand",   "分步指南：如何移居泰国"),
    ("Step-by-Step: How to Move to Japan",      "分步指南：如何移居日本"),
    ("Step-by-Step: How to Move to Vietnam",    "分步指南：如何移居越南"),
    ("Step-by-Step: How to Move to Malaysia",   "分步指南：如何移居马来西亚"),
    ("Step-by-Step: How to Move to Cambodia",   "分步指南：如何移居柬埔寨"),
    ("Step-by-Step: How to Move to Laos",       "分步指南：如何移居老挝"),
    ("Step-by-Step: How to Move to Greece",     "分步指南：如何移居希腊"),
    ("Step-by-Step: How to Move to Spain",      "分步指南：如何移居西班牙"),
    ("Step-by-Step: How to Move to Portugal",   "分步指南：如何移居葡萄牙"),
    ("Step-by-Step: How to Move to Mexico",     "分步指南：如何移居墨西哥"),
    ("Step-by-Step: How to Move to Costa Rica", "分步指南：如何移居哥斯达黎加"),
    ("Step-by-Step: How to Move to Panama",     "分步指南：如何移居巴拿马"),
    ("Step-by-Step: How to Move to Paraguay",   "分步指南：如何移居巴拉圭"),
    ("Step-by-Step: How to Move to UAE",        "分步指南：如何移居阿联酋"),
    ("Step-by-Step Process",            "分步流程"),
    ("Frequently Asked Questions",      "常见问题"),
    ("&#128176; Tax &amp; Fiscal Exile","&#128176; 税务与财务移民"),
    ("Tax &amp; Fiscal Exile",          "税务与财务移民"),
    ("Tax & Fiscal Exile",              "税务与财务移民"),
    ("🏥 Healthcare in Georgia",        "🏥 格鲁吉亚医疗保健"),
    ("🛡️ Health Insurance in Georgia",  "🛡️ 格鲁吉亚健康保险"),
    ("🏦 Opening a Bank Account in Georgia", "🏦 在格鲁吉亚开设银行账户"),
    ("🏠 Buying Property in Georgia",   "🏠 在格鲁吉亚购买房产"),
    ("Healthcare in",                   "医疗保健 —"),
    ("Health Insurance",                "健康保险"),
    ("Banking in",                      "银行业务 —"),
    ("Real Estate in",                  "房地产 —"),
    ("Cost of Living",                  "生活成本"),
    ("Pro Tips",                        "专业建议"),
    ("Key Tax Points",                  "主要税务要点"),
    ("Official Sources &amp; References",  "官方来源与参考资料"),
    ("&#128218; Official Sources &amp; References", "&#128218; 官方来源与参考资料"),

    # ── FULL VISA GUIDE LINKS ─────────────────────────────────────────────────
    ("→ Full Thailand Visa Requirements &amp; Application Guide",
     "→ 完整泰国签证要求与申请指南"),
    ("→ Full Thailand Visa Requirements & Application Guide",
     "→ 完整泰国签证要求与申请指南"),
    ("→ Full Japan Visa Requirements Guide",
     "→ 完整日本签证要求指南"),
    ("→ Full Vietnam Visa Requirements Guide",
     "→ 完整越南签证要求指南"),
    ("→ Full Malaysia Visa Requirements Guide",
     "→ 完整马来西亚签证要求指南"),
    ("→ Full Cambodia Visa Requirements Guide",
     "→ 完整柬埔寨签证要求指南"),
    ("→ Full Laos Visa Requirements Guide",
     "→ 完整老挝签证要求指南"),
    ("→ Full Georgia Visa Requirements Guide",
     "→ 完整格鲁吉亚签证要求指南"),
    ("→ Full Greece Visa Requirements Guide",
     "→ 完整希腊签证要求指南"),
    ("→ Full Spain Visa Requirements Guide",
     "→ 完整西班牙签证要求指南"),
    ("→ Full Portugal Visa Requirements Guide",
     "→ 完整葡萄牙签证要求指南"),
    ("→ Full Mexico Visa Requirements Guide",
     "→ 完整墨西哥签证要求指南"),
    ("→ Full Colombia Visa Requirements Guide",
     "→ 完整哥伦比亚签证要求指南"),
    ("→ Full Costa Rica Visa Requirements Guide",
     "→ 完整哥斯达黎加签证要求指南"),
    ("→ Full Panama Visa Requirements Guide",
     "→ 完整巴拿马签证要求指南"),
    ("→ Full Paraguay Visa Requirements Guide",
     "→ 完整巴拉圭签证要求指南"),
    ("→ Full UAE Visa Requirements Guide",
     "→ 完整阿联酋签证要求指南"),

    # ── KEY FACTS TABLE HEADERS ────────────────────────────────────────────────
    ("<strong>Capital</strong>",   "<strong>首都</strong>"),
    ("<strong>Currency</strong>",  "<strong>货币</strong>"),
    ("<strong>Language</strong>",  "<strong>语言</strong>"),
    ("<strong>Schengen</strong>",  "<strong>申根区</strong>"),
    # Georgia table (td style)
    (">Capital<",    ">首都<"),
    (">Currency<",   ">货币<"),
    (">Language<",   ">语言<"),
    (">Monthly cost<", ">月均花费<"),
    (">Time Zone<",  ">时区<"),
    (">Climate<",    ">气候<"),

    # ── STEP HEADINGS ─────────────────────────────────────────────────────────
    # Thailand steps
    ("Choose your visa type",
     "选择您的签证类型"),
    ("Gather required documents",
     "收集所需文件"),
    ("Apply at a Thai embassy or consulate",
     "在泰国大使馆或领事馆提出申请"),
    ("Arrive and register your address",
     "抵达并登记您的地址"),
    ("Open a Thai bank account",
     "开设泰国银行账户"),
    ("Get health insurance",
     "获取健康保险"),
    ("Annual extension / 90-day report",
     "年度延期 / 90天报告"),
    # Japan steps
    ("Apply for Certificate of Eligibility (CoE)",
     "申请资格认定证明书（CoE）"),
    ("Apply for your visa at Japanese embassy",
     "在日本大使馆申请签证"),
    ("Register at your ward/city office (My Number)",
     "在区/市政办公室登记（My Number）"),
    ("Open a Japanese bank account",
     "开设日本银行账户"),
    ("Get National Health Insurance (Kokumin Kenko Hoken)",
     "参加国民健康保险（国民健康保険）"),
    ("Get your Residence Card (Zairyu Card)",
     "领取居留卡（在留卡）"),
    ("Register your address (Juusho Touroku)",
     "登记您的住址（住所登録）"),
    # Vietnam steps
    ("Apply for E-Visa online",
     "在线申请电子签证"),
    ("Register your accommodation",
     "登记住所"),
    ("Get a Vietnamese SIM card",
     "购买越南SIM卡"),
    ("Open a bank account",
     "开设银行账户"),
    ("Apply for Temporary Residence Card",
     "申请临时居留证"),
    ("Register for tax if working locally",
     "如在当地工作则注册税务"),
    # Malaysia steps
    ("Apply for DE Rantau or MM2H",
     "申请DE Rantau或MM2H"),
    ("Arrive on social visit pass",
     "以社交访问证抵达"),
    ("Open a Malaysian bank account",
     "开设马来西亚银行账户"),
    ("Register with LHDN (tax authority)",
     "向LHDN（税务机构）注册"),
    ("Register your address",
     "登记住址"),
    ("Get a Malaysian driving licence",
     "办理马来西亚驾驶执照"),
    # Spain steps
    ("Apply for your visa",
     "申请签证"),
    ("Get your NIE (Foreigners' Identity Number)",
     "办理NIE（外国人身份证号码）"),
    ("Register on the Padrón Municipal",
     "在市政登记册（Padrón Municipal）登记"),
    ("Open a Spanish bank account",
     "开设西班牙银行账户"),
    ("Apply for Tarjeta de Identidad de Extranjero (TIE)",
     "申请外国人身份证（TIE）"),
    ("Register with public healthcare (INSS)",
     "向公共医疗（INSS）注册"),
    ("Tax registration (Hacienda)",
     "税务注册（Hacienda）"),

    # ── TAX SECTION CARD LABELS ────────────────────────────────────────────────
    ("Capital Gains Tax",       "资本利得税"),
    ("Tax Regime",              "税务制度"),
    ("Crypto-Friendliness",     "加密货币友好度"),
    ("Exit Tax",                "离境税"),
    ("Simulate Your Tax Savings", "模拟您的税务节省"),
    ("Use our free tax exile simulator to compare your tax savings in Thailand.",
     "使用我们的免费财务移民模拟器，比较您在泰国的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Japan.",
     "使用我们的免费财务移民模拟器，比较您在日本的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Vietnam.",
     "使用我们的免费财务移民模拟器，比较您在越南的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Malaysia.",
     "使用我们的免费财务移民模拟器，比较您在马来西亚的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Cambodia.",
     "使用我们的免费财务移民模拟器，比较您在柬埔寨的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Laos.",
     "使用我们的免费财务移民模拟器，比较您在老挝的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Georgia.",
     "使用我们的免费财务移民模拟器，比较您在格鲁吉亚的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Greece.",
     "使用我们的免费财务移民模拟器，比较您在希腊的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Spain.",
     "使用我们的免费财务移民模拟器，比较您在西班牙的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Portugal.",
     "使用我们的免费财务移民模拟器，比较您在葡萄牙的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Mexico.",
     "使用我们的免费财务移民模拟器，比较您在墨西哥的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Colombia.",
     "使用我们的免费财务移民模拟器，比较您在哥伦比亚的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Costa Rica.",
     "使用我们的免费财务移民模拟器，比较您在哥斯达黎加的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Panama.",
     "使用我们的免费财务移民模拟器，比较您在巴拿马的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in Paraguay.",
     "使用我们的免费财务移民模拟器，比较您在巴拉圭的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in UAE.",
     "使用我们的免费财务移民模拟器，比较您在阿联酋的税务节省。"),
    ("Use our free tax exile simulator to compare your tax savings in UAE.",
     "使用我们的免费财务移民模拟器，比较您在阿联酋的税务节省。"),
    ("Compare tax rates across 27+ countries with our interactive simulator",
     "使用我们的互动模拟器比较27个以上国家的税率"),
    ("&#128640; Simulate Your Tax Savings &rarr;",
     "&#128640; 模拟您的税务节省 &rarr;"),
    ("Tax information provided for general guidance only. Consult a qualified tax advisor before making relocation decisions.",
     "税务信息仅供一般参考。在做出移居决定前，请咨询合格的税务顾问。"),

    # ── AUTHOR BOX ─────────────────────────────────────────────────────────────
    ("Editorial Team — eVisa-Card.com",
     "编辑团队 — eVisa-Card.com"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Thailand.",
     "侨民指南由旅游专家、移民专家和具有泰国第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Spain.",
     "侨民指南由旅游专家、移民专家和具有西班牙第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Georgia.",
     "侨民指南由旅游专家、移民专家和具有格鲁吉亚第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Portugal.",
     "侨民指南由旅游专家、移民专家和具有葡萄牙第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Greece.",
     "侨民指南由旅游专家、移民专家和具有希腊第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Mexico.",
     "侨民指南由旅游专家、移民专家和具有墨西哥第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Panama.",
     "侨民指南由旅游专家、移民专家和具有巴拿马第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Paraguay.",
     "侨民指南由旅游专家、移民专家和具有巴拉圭第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Costa Rica.",
     "侨民指南由旅游专家、移民专家和具有哥斯达黎加第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in UAE.",
     "侨民指南由旅游专家、移民专家和具有阿联酋第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Colombia.",
     "侨民指南由旅游专家、移民专家和具有哥伦比亚第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Cambodia.",
     "侨民指南由旅游专家、移民专家和具有柬埔寨第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Laos.",
     "侨民指南由旅游专家、移民专家和具有老挝第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Malaysia.",
     "侨民指南由旅游专家、移民专家和具有马来西亚第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Vietnam.",
     "侨民指南由旅游专家、移民专家和具有越南第一手经验的侨民撰写。"),
    ("Expat guides written by travel experts, immigration specialists and expats with first-hand experience in Japan.",
     "侨民指南由旅游专家、移民专家和具有日本第一手经验的侨民撰写。"),
    ("&#x2714; Verified information",   "&#x2714; 经过核实的信息"),
    ("&#x2714; Updated March 2026",     "&#x2714; 2026年3月更新"),
    ("&#x2714; Official sources cited", "&#x2714; 引用官方来源"),

    # ── PRACTICAL INFO GRID HEADERS ───────────────────────────────────────────
    ("🏠 Housing",      "🏠 住房"),
    ("🏦 Banking",      "🏦 银行业务"),
    ("🏥 Healthcare",   "🏥 医疗保健"),
    ("💰 费用 of Living", "💰 生活成本"),

    # ── THAILAND CONTENT ──────────────────────────────────────────────────────
    ("Thailand offers several long-stay options: the Tourist Visa (60 days, extendable), Non-Immigrant O-A Retirement Visa (1 year, renewable, for 50+), Thailand Elite Visa (5–20 years, premium), Long-Term Resident (LTR) Visa for professionals and digital nomads. There is no standard permanent residency path but long-term visa holders can renew indefinitely.",
     "泰国提供多种长期居留选项：旅游签证（60天，可延期）、非移民O-A退休签证（1年，可续签，50岁以上）、泰国精英签证（5至20年，高端）、面向专业人士和数字游民的长期居留（LTR）签证。目前没有标准的永久居留途径，但长期签证持有人可无限期续签。"),
    ("Determine if you qualify for the Retirement O-A (50+, pension/savings proof), LTR Visa (remote worker, $80k income), or Thailand Elite. Most expats start with a Tourist Visa and switch after arrival.",
     "确定您是否符合退休O-A（50岁以上，需提供养老金/储蓄证明）、LTR签证（远程工作者，收入8万美元）或泰国精英签证的资格。大多数侨民从旅游签证开始，抵达后再转换。"),
    ("Passport (6+ months validity), passport photos, bank statements (800,000 THB in Thai bank for retirement visa or proof of $80k income for LTR), health insurance, medical certificate.",
     "护照（有效期6个月以上）、护照照片、银行对账单（退休签证需在泰国银行存有80万泰铢，或LTR需提供8万美元收入证明）、健康保险、医疗证明。"),
    ("Submit your visa application at your nearest Thai embassy. Processing takes 3–5 business days. You can also enter on a tourist visa and extend at the Immigration Bureau in Thailand.",
     "在最近的泰国大使馆提交签证申请。处理时间为3至5个工作日。您也可以以旅游签证入境，并在泰国移民局延期。"),
    ("Within 24 hours of arriving, notify your accommodation. If renting, your landlord must file a TM.30 report. You receive a TM.6 arrival card.",
     "抵达后24小时内，通知您的住所。如果租房，房东必须提交TM.30报告。您将收到TM.6入境卡。"),
    ("Open a Kasikorn Bank (KBank) or Bangkok Bank account. You'll need your passport, Non-Immigrant visa, and proof of address. Required for the 800,000 THB retirement deposit.",
     "开设开泰银行（KBank）或曼谷银行账户。您需要护照、非移民签证和地址证明。退休存款80万泰铢是必须的。"),
    ("Mandatory for retirement and LTR visas. Compare providers: Pacific Cross, BUPA Thailand, AXA. Budget ฿15,000–฿60,000/year depending on age and coverage.",
     "退休签证和LTR签证为强制要求。比较各保险公司：Pacific Cross、泰国BUPA、AXA。根据年龄和保障范围，预算每年1.5万至6万泰铢。"),
    ("Renew your visa annually at the local Immigration office. File 90-day reports in person, by post, or online via the Immigration Bureau website.",
     "每年在当地移民局续签签证。可以亲自、邮寄或通过移民局网站在线提交90天报告。"),
    ("Bangkok studio: ฿8,000–฿15,000/month. Chiang Mai 1-bed: ฿6,000–฿12,000/month. Phuket condo: ฿12,000–฿25,000/month. Foreigners cannot own land but can own condo units (49% foreign quota per building).",
     "曼谷单间公寓：每月8,000至15,000泰铢。清迈一室公寓：每月6,000至12,000泰铢。普吉岛公寓：每月12,000至25,000泰铢。外国人不能拥有土地，但可以拥有公寓单元（每栋楼外籍人士配额49%）。"),
    ("Major banks: Kasikorn (KBank), Bangkok Bank, SCB. Open with Non-Immigrant visa + passport. Online banking available in English. Wise and Revolut are popular for international transfers.",
     "主要银行：开泰银行（KBank）、曼谷银行、暹罗商业银行。凭非移民签证+护照开户。网上银行提供英文服务。Wise和Revolut是常用的国际转账工具。"),
    ("Excellent private hospitals (Bumrungrad, BNH, Samitivej) with English-speaking staff. Private health insurance required for most long-stay visas. 费用s significantly lower than Western countries.",
     "优秀的私立医院（康民国际医院、BNH、三美泰医院）配备英语工作人员。大多数长期签证需要私人健康保险。费用远低于西方国家。"),
    ("Budget: ฿30,000–฿40,000/month ($850–$1,100). Comfortable: ฿60,000–฿90,000/month ($1,700–$2,500). Luxury: ฿120,000+/month. Chiang Mai cheaper than Bangkok or Phuket.",
     "经济型：每月3万至4万泰铢（850至1,100美元）。舒适型：每月6万至9万泰铢（1,700至2,500美元）。豪华型：每月12万泰铢以上。清迈比曼谷或普吉岛便宜。"),

    # ── THAILAND FAQ CONTENT ───────────────────────────────────────────────────
    ("Can foreigners work in Thailand?",
     "外国人可以在泰国工作吗？"),
    ("Yes, with a work permit. Remote workers can use the LTR Visa to work for overseas employers legally without a Thai work permit.",
     "可以，需持工作许可证。远程工作者可以使用LTR签证，为海外雇主合法工作，无需泰国工作许可证。"),
    ("What is the minimum income for a retirement visa?",
     "退休签证的最低收入要求是多少？"),
    ("You need to show 800,000 THB (~$22,000) in a Thai bank account, OR a monthly income/pension of 65,000 THB (~$1,800), OR a combination totaling 800,000 THB.",
     "您需要在泰国银行账户中存入80万泰铢（约22,000美元），或每月收入/养老金6.5万泰铢（约1,800美元），或两者合计达到80万泰铢。"),
    ("Can I bring my spouse?",
     "我可以携带配偶吗？"),
    ("Yes. Your spouse can apply for a Non-Immigrant O visa as a dependent. They will need to do 90-day reports and annual extensions as well.",
     "可以。您的配偶可以作为受抚养人申请非移民O类签证。他们也需要提交90天报告并进行年度延期。"),
    ("Is Thailand safe for expats?",
     "泰国对侨民来说安全吗？"),
    ("Thailand is generally safe for expats. Petty crime exists in tourist areas. Natural disasters (floods, occasional storms) can affect some regions.",
     "泰国对侨民来说总体上是安全的。旅游区存在小型犯罪。自然灾害（洪水、偶发风暴）可能影响某些地区。"),
    ("Do I need to speak Thai?",
     "我需要会说泰语吗？"),
    ("Not necessary in major cities and tourist areas. English is widely spoken in Bangkok, Chiang Mai and Phuket. Learning basic Thai is appreciated and helpful.",
     "在大城市和旅游区不是必须的。英语在曼谷、清迈和普吉岛广泛使用。学习基础泰语会受到欢迎并有所帮助。"),
    ("15% flat tax on capital gains realized in Thailand",
     "在泰国实现的资本利得征收15%统一税"),
    ("No tax on gains from assets held before moving to Thailand",
     "移居泰国前持有的资产收益免税"),
    ("LTR Visa holders: 17% flat income tax rate",
     "LTR签证持有人：17%统一所得税率"),
    ("No inheritance tax under 100M THB",
     "1亿泰铢以下无遗产税"),

    # ── JAPAN FAQ CONTENT ─────────────────────────────────────────────────────
    ("Is there a digital nomad visa for Japan?",
     "日本有数字游民签证吗？"),
    ("Yes — Japan launched a Digital Nomad Visa in March 2024. Requirements: income ≥ JPY 10,000,000/year (~$68k), valid health insurance, from one of 50+ eligible countries. Valid 6 months, non-renewable.",
     "有的——日本于2024年3月推出了数字游民签证。要求：年收入≥1,000万日元（约6.8万美元），有效健康保险，来自50个以上符合条件的国家。有效期6个月，不可续签。"),
    ("How do I get permanent residency in Japan?",
     "如何在日本获得永久居留权？"),
    ("Standard path: 10 years of continuous legal residency. Fast track: HSP (Highly Skilled Professional) Visa holders can qualify in 1-3 years with high points.",
     "标准途径：持续合法居留10年。快速通道：高技能专业人员（HSP）签证持有人可在1至3年内凭高积分获得资格。"),
    ("Can foreigners buy property in Japan?",
     "外国人可以在日本购买房产吗？"),
    ("Yes, with no restrictions. Foreigners can freely buy real estate. Rural areas have very affordable properties. Tokyo condos: ¥30-80M.",
     "可以，没有限制。外国人可以自由购买房地产。农村地区房产价格非常实惠。东京公寓：3,000至8,000万日元。"),
    ("Do I need to speak Japanese?",
     "我需要会说日语吗？"),
    ("Highly recommended. Japan has limited English infrastructure outside tourist areas. Japanese language skills significantly expand job and social opportunities.",
     "强烈推荐。日本在旅游区以外的英语基础设施有限。日语能力可以显著拓展就业和社交机会。"),
    ("Is Japan safe?",
     "日本安全吗？"),
    ("Exceptionally safe. Japan consistently ranks #1-3 globally for safety. Extremely low violent crime and theft.",
     "极其安全。日本在全球安全排名中持续位居第1至第3位。暴力犯罪和盗窃率极低。"),
    ("Tokyo 1K (studio): ¥60,000-¥120,000/month ($400-$800). Osaka: ¥45,000-¥90,000/month. Fukuoka: ¥40,000-¥80,000/month. Gaijin Houses (shared) from ¥30,000/month. Guarantor (hoshounin) or guarantor agency required for renting.",
     "东京1K（单间）：每月6万至12万日元（400至800美元）。大阪：每月4.5万至9万日元。福冈：每月4万至8万日元。外国人共享住宅（Gaijin Houses）每月3万日元起。租房需要担保人（保証人）或担保机构。"),
    ("Japan Post Bank (easiest to open), Shinsei Bank (English support), SMBC. Open with residence card + My Number. 7-Eleven ATMs accept international cards 24/7. Wise essential for international transfers.",
     "日本邮储银行（最容易开户）、新生银行（英文支持）、三井住友银行。凭居留卡+My Number开户。7-Eleven ATM全天候接受国际卡。Wise是国际转账的必备工具。"),
    ("National Health Insurance covers 70% of medical costs. Excellent private hospitals. Average GP visit: ¥2,000-¥5,000. Dental: ¥2,000-¥8,000. One of world's best healthcare systems.",
     "国民健康保险覆盖70%的医疗费用。私立医院优秀。平均全科医生就诊费：2,000至5,000日元。牙科：2,000至8,000日元。是世界上最好的医疗保健体系之一。"),
    ("Tokyo (comfortable): ¥250,000-¥400,000/month ($1,700-$2,700). Osaka: ¥200,000-¥320,000/month. Fukuoka: ¥170,000-¥280,000/month. Food and transport are reasonable; housing is the main cost.",
     "东京（舒适型）：每月25万至40万日元（1,700至2,700美元）。大阪：每月20万至32万日元。福冈：每月17万至28万日元。食品和交通费用合理；住房是主要开销。"),

    # ── VIETNAM FAQ CONTENT ────────────────────────────────────────────────────
    ("Can I work remotely in Vietnam?",
     "我可以在越南远程工作吗？"),
    ("Yes. No work permit is required for remote workers earning income from foreign sources. The e-Visa or TRC covers remote work.",
     "可以。从外国来源获得收入的远程工作者不需要工作许可证。电子签证或临时居留证涵盖远程工作。"),
    ("Can foreigners own property in Vietnam?",
     "外国人可以在越南拥有房产吗？"),
    ("Foreigners can own apartments for 50 years (renewable) but not land. Limited to 30% of units per building.",
     "外国人可以拥有公寓50年（可续期），但不能拥有土地。每栋楼限制30%的单元。"),
    ("Is Vietnam safe for expats?",
     "越南对侨民来说安全吗？"),
    ("Very safe. Traffic (motorbikes) is the main risk. Violent crime against foreigners is extremely rare.",
     "非常安全。交通（摩托车）是主要风险。针对外国人的暴力犯罪极为罕见。"),
    ("How do I extend my e-Visa?",
     "如何延长我的电子签证？"),
    ("Apply for a new e-Visa at evisa.gov.vn before expiry, or obtain a TRC for longer stays.",
     "在到期前在evisa.gov.vn申请新的电子签证，或获取临时居留证以延长居留时间。"),
    ("Do I need to learn Vietnamese?",
     "我需要学习越南语吗？"),
    ("Not mandatory in major cities and expat areas where English is widely spoken.",
     "在英语广泛使用的大城市和侨民聚居区不是强制要求的。"),
    ("Hanoi 1-bed: $300-$700/month. HCMC District 1/2: $500-$1,200/month. Da Nang: $400-$800/month. Hoi An: $350-$700/month. Furnished serviced apartments widely available.",
     "河内一室公寓：每月300至700美元。胡志明市第1/2区：每月500至1,200美元。岘港：每月400至800美元。会安：每月350至700美元。配家具的服务式公寓广泛提供。"),
    ("Vietcombank, Techcombank, BIDV, VPBank. Open with passport + valid visa. Wise popular for international transfers. Cash still widely used in smaller areas.",
     "越南外贸银行、科技商业银行、越南投资发展银行、VPBank。凭护照+有效签证开户。Wise在国际转账中很受欢迎。现金在小地方仍广泛使用。"),
    ("No public healthcare for foreign residents. Private hospitals: FV Hospital (HCMC), Vinmec, Hanoi Family Medical Practice. Private insurance $200-$600/year. 费用s 70-80% lower than USA.",
     "外国居民无公共医疗保健。私立医院：法越医院（胡志明市）、Vinmec、河内家庭医疗。私人保险每年200至600美元。费用比美国低70至80%。"),
    ("Budget: $700-$1,000/month. Comfortable: $1,200-$2,000/month. Luxury: $2,500+/month. Vietnam is one of the world's most affordable expat destinations.",
     "经济型：每月700至1,000美元。舒适型：每月1,200至2,000美元。豪华型：每月2,500美元以上。越南是全球最实惠的侨民目的地之一。"),

    # ── SPAIN CONTENT ─────────────────────────────────────────────────────────
    ("Key options: Non-Lucrative Visa (NLV) — no work, passive income ≥ €2,400/month; Digital Nomad Visa (Startup Act 2023) — remote work for non-Spanish employers, income ≥ €2,334/month; Golden Visa — property investment ≥ €500k (under review); EU citizens register at local Foreigner's Office (Oficina de Extranjeros).",
     "主要选项：非营利签证（NLV）——不得工作，被动收入≥每月2,400欧元；数字游民签证（2023年创业法）——为非西班牙雇主远程工作，收入≥每月2,334欧元；黄金签证——房产投资≥50万欧元（审查中）；欧盟公民在当地外国人办公室（Oficina de Extranjeros）注册。"),
    ("What is the Non-Lucrative Visa income requirement?",
     "非营利签证的收入要求是多少？"),
    ("€2,400/month for the main applicant (2024 figure), plus €600 for each additional family member. Must be passive income: pension, dividends, rental income.",
     "主申请人每月2,400欧元（2024年数据），每增加一名家庭成员加600欧元。必须是被动收入：养老金、股息、租金收入。"),
    ("Can I work in Spain on a Non-Lucrative Visa?",
     "持非营利签证可以在西班牙工作吗？"),
    ("No. The NLV prohibits working in Spain. To work remotely for non-Spanish clients, apply for the Digital Nomad Visa instead.",
     "不可以。非营利签证禁止在西班牙工作。如需为非西班牙客户远程工作，请申请数字游民签证。"),
    ("How long does it take to get permanent residency?",
     "获得永久居留权需要多长时间？"),
    ("5 years of continuous legal residency. Spanish citizenship requires 10 years (2 years for citizens of Spanish-speaking countries).",
     "持续合法居留5年。西班牙国籍需要10年（讲西班牙语国家的公民需要2年）。"),
    ("Is Spain safe for expats?",
     "西班牙对侨民来说安全吗？"),
    ("Yes — Spain consistently ranks among the safest countries in the world. Low violent crime, excellent infrastructure.",
     "是的——西班牙始终位居全球最安全国家之列。暴力犯罪率低，基础设施优良。"),
    ("Do I need to speak Spanish?",
     "我需要会说西班牙语吗？"),
    ("Madrid 1-bed: €1,200–€1,800/month. Barcelona 1-bed: €1,300–€2,000/month. Valencia/Alicante: €700–€1,100/month. Interior cities (Seville, Málaga): €700–€1,200/month. Short-term furnished flats common via Idealista, Fotocasa.",
     "马德里一室公寓：每月1,200至1,800欧元。巴塞罗那一室公寓：每月1,300至2,000欧元。巴伦西亚/阿利坎特：每月700至1,100欧元。内陆城市（塞维利亚、马拉加）：每月700至1,200欧元。通过Idealista、Fotocasa可常见短期配家具公寓。"),
    ("Main banks: Santander, BBVA, CaixaBank, Sabadell. Open with NIE + passport. Revolut and Wise widely used. Many banks offer English-language services in expat areas.",
     "主要银行：桑坦德银行、BBVA、拉凯沙银行、萨瓦德尔银行。凭NIE+护照开户。Revolut和Wise广泛使用。许多银行在侨民聚居区提供英语服务。"),
    ("Excellent public SNS (Sistema Nacional de Salud) for registered residents. World-class private hospitals. Private insurance: €50–€200/month. Sanitas, Adeslas, AXA popular for expats.",
     "为已登记居民提供优秀的公共国家健康体系（SNS）。世界级私立医院。私人保险：每月50至200欧元。Sanitas、Adeslas、AXA在侨民中很受欢迎。"),
    ("Madrid/Barcelona: €2,500–€4,000/month couple. Valencia/Alicante: €1,800–€2,800/month. Rural inland: €1,200–€2,000/month. Spain is ~25% cheaper than UK, France or Germany.",
     "马德里/巴塞罗那（夫妻）：每月2,500至4,000欧元。巴伦西亚/阿利坎特：每月1,800至2,800欧元。农村内陆：每月1,200至2,000欧元。西班牙比英国、法国或德国便宜约25%。"),
    ("Beckham Law: 24% flat tax for first 6 years",
     "贝克汉姆法：前6年24%统一税率"),
    ("Progressive CGT: 19% (0-6k), 21% (6-50k), 23% (50-200k), 28% (200k+)",
     "累进资本利得税：19%（0至6千欧元），21%（6千至5万欧元），23%（5万至20万欧元），28%（20万欧元以上）"),
    ("Exit tax applies if resident > 4 years with > 4M in assets",
     "居住超过4年且资产超过400万欧元时适用离境税"),
    ("Modelo 720: mandatory declaration of foreign assets > 50k",
     "720表格：必须申报超过5万欧元的境外资产"),

    # ── GENERIC PATTERNS ──────────────────────────────────────────────────────
    ("Options:",                "选项："),
    ("Key options:",            "主要选项："),
    ("Retirement Visa Guide",   "退休签证指南"),
    ("Cheapest Countries to Retire", "最便宜的退休国家"),
    ("All Expat Guides",        "所有侨民指南"),
    ("Table of Contents",       "目录"),
    ("Visa &amp; Residency",    "签证与居留"),
    ("Healthcare",              "医疗保健"),
    ("Health Insurance",        "健康保险"),
    ("Bank Account",            "银行账户"),
    ("Buying Property",         "购买房产"),
    ("Step-by-Step: How to Move to",  "分步指南：如何移居"),
    ("How to Move to",          "如何移居"),
    ("Last updated: March 2026",  "最后更新：2026年3月"),
    ("March 2026",              "2026年3月"),
    ("Mandatory",               "强制性"),
    ("Recommended",             "推荐"),
    ("Optional",                "可选"),
    ("per year",                "每年"),
    ("per month",               "每月"),
    ("per night",               "每晚"),
    ("Visa Type",               "签证类型"),
    ("Stay",                    "停留时间"),
    ("Requirements",            "要求"),
    ("Best For",                "最适合"),
    ("Fee",                     "费用"),
    ("Processing",              "处理时间"),
    ("Duration",                "期限"),
    ("Notes",                   "备注"),
    # "Yes" / "No" in colored spans (only translate standalone text in table cells)
    (">Yes (> 100M JPY in assets)<",  ">是（资产超过1亿日元）<"),
    (">Yes (> 4 years residency, > 4M assets)<", ">是（居住超过4年，资产超过400万）<"),
    # Generic single-word Yes/No only in specific spans
    ("font-weight:600;color:#28a745;\">No<",  "font-weight:600;color:#28a745;\">否<"),
    ("font-weight:600;color:#dc3545;\">Yes",  "font-weight:600;color:#dc3545;\">是"),
    # Tax regime values
    ("Territorial",             "领土制"),
    ("Worldwide",               "全球制"),
    ("Undefined",               "未定义"),
    # Georgia specific
    ("Territorial + Small Business",  "领土制 + 小企业"),
    # Georgia intro card
    ("Monthly cost",            "月均花费"),
    # Georgia TOC
    ("Visa &amp; Residency",    "签证与居留"),
    # Georgia healthcare table header
    (">Service<",               ">服务<"),
    (">Cost<",                  ">费用<"),
    # General table items (if exact match)
    ("Emergency (private hospital)",            "急诊（私立医院）"),
    ("Hospitalisation (private, per night)",    "住院（私立，每晚）"),
    ("Basic blood tests",                       "基础血液检测"),
    ("Property registration fee",               "房产登记费"),
    ("Annual property tax",                     "年度房产税"),
    ("No real estate transfer tax",             "无房产转让税"),
    # General content / author box
    ("Verified information",        "经过核实的信息"),
    ("Official sources cited",      "引用官方来源"),
    ("This guide is researched and maintained by the editorial team at eVisa-Card.com.",
     "本指南由eVisa-Card.com编辑团队研究和维护。"),
    ("Always verify current requirements with official government sources and consult a licensed professional before making major decisions.",
     "在做出重大决定之前，请始终向官方政府来源核实当前要求，并咨询持牌专业人员。"),
    ("Powered by",              "由"),

    # ── COLOMBIA CONTENT ──────────────────────────────────────────────────────
    ("Colombia at a Glance",    "哥伦比亚概况"),
    ("Capital",                 "首都"),
    ("Currency",                "货币"),
    ("Language",                "语言"),
    ("Time Zone",               "时区"),
    ("Climate",                 "气候"),

    # ── FOOTER ────────────────────────────────────────────────────────────────
    ("Global eVisa &amp; Travel Information Platform",
     "全球电子签证与旅行信息平台"),
    ("Global eVisa & Travel Information Platform",
     "全球电子签证与旅行信息平台"),
    ("Follow eVisa-Card.com",   "关注 eVisa-Card.com"),

    # ── JAPAN STEP BODY PARAGRAPHS (remaining English in step detail paragraphs) ──
    ("Your Japanese sponsor (employer/school/family) applies at the 入国管理局服务机构. 处理时间: 1-3 months. Required for most long-stay visas.",
     "您的日本担保人（雇主/学校/家庭）在入国管理局服务机构提出申请。处理时间：1至3个月。大多数长期签证均需要此证明。"),
    ("Present CoE + passport + visa application form + photos. 处理时间: 5-7 business days after CoE.",
     "提交CoE+护照+签证申请表+照片。获得CoE后处理时间：5至7个工作日。"),
    ("Within 14 days of arrival, register at your local ward office. You receive My Number (national ID) and national health insurance card.",
     "抵达后14天内，在当地区政府办公室登记。您将收到My Number（国家身份证号码）和国民健康保险卡。"),
    ("Open with Japan Post Bank (easiest for new residents), Shinsei Bank, or SMBC. Required: passport, residence card, My Number.",
     "在日本邮储银行（对新居民最方便）、新生银行或三井住友银行开户。所需：护照、居留卡、My Number。"),
    ("Get National 健康保险 (Kokumin Kenko Hoken)",
     "参加国民健康保险（Kokumin Kenko Hoken）"),
    ("National 健康保险 covers 70% of medical costs. Excellent private hospitals. Average GP visit: ¥2,000-¥5,000. Dental: ¥2,000-¥8,000. One of world's best healthcare systems.",
     "国民健康保险覆盖70%的医疗费用。私立医院优秀。平均全科医生就诊费：2,000至5,000日元。牙科：2,000至8,000日元。是世界上最好的医疗保健体系之一。"),
    ("Register at ward office. Premiums based on income. Covers 70% of medical costs. Top-up private insurance available.",
     "在区政府办公室登记。保费根据收入计算。覆盖70%的医疗费用。可附加私人保险。"),
    ("Issued at the airport upon arrival with your visa. Carry at all times — required by law.",
     "抵达时在机场随签证颁发。必须随时携带——法律要求。"),
    ("Register your exact address at the ward office within 14 days. Required to receive your My Number and access services.",
     "在14天内在区政府办公室登记您的确切地址。领取My Number和访问各类服务均需此项登记。"),

    # ── MISC remaining English in 费用 fields (partial Chinese already there) ──
    # The word "费用" (Cost) was already partially translated in some files —
    # these patterns clean up any remaining English in those hybrid strings:
    ("<strong>费用 of Living</strong>",  "<strong>生活成本</strong>"),
    (">费用 of Living<",         ">生活成本<"),
    ('"费用 of Living"',         '"生活成本"'),
    ("💰 费用 of Living",        "💰 生活成本"),
    ("🏥 费用s",                 "🏥 费用"),
    ("Typical 费用s",            "典型费用"),
    # Lingering partial translations in Georgia
    ("Private 全科医生咨询",      "私人全科医生咨询"),
    ("费用a del Sol",             "太阳海岸"),
    ("费用a Blanca",              "白海岸"),
    # Immigration Services Agency in Japan guide
    ("Immigration 服务s Agency",  "入国管理局服务机构"),
    ("Public 服务 Hall",          "公共服务大厅"),
    ("Revenue 服务",              "税务服务"),
]


def main():
    files = [f for f in sorted(os.listdir(BASE))
             if f.startswith("expat-guide-") and f.endswith(".html")]
    print(f"Found {len(files)} files to process.\n")
    changed = 0
    for fname in files:
        fpath = os.path.join(BASE, fname)
        with open(fpath, encoding="utf-8", errors="ignore") as f:
            html = f.read()
        original = html
        for eng, chi in REPLACEMENTS:
            html = html.replace(eng, chi)
        if html != original:
            with open(fpath, "w", encoding="utf-8") as f:
                f.write(html)
            print(f"OK  {fname}")
            changed += 1
        else:
            print(f"--  {fname}  (no changes)")
    print(f"\nDone. {changed}/{len(files)} files updated.")


if __name__ == "__main__":
    main()
