#!/usr/bin/env python3
"""
Fix hreflang + lang dropdown in guide pages.
- EN/FR/ES/PT pages: add zh/th/ru/ar/ja/ko to hreflang, fix dropdown links
- zh/th/ru/ar/ja/ko pages: already have full hreflang (generated by gen script)
"""
import os, re, sys
sys.stdout.reconfigure(encoding='utf-8')

WWW = "C:/Users/chemi/Documents/evisa/pacific-main/www"
BASE = "https://www.evisa-card.com"

ALL_LANGS = ["en","fr","es","pt","zh","th","ru","ar","ja","ko"]
NEW_LANGS = ["zh","th","ru","ar","ja","ko"]

GUIDE_FILES = [
    "best-countries-digital-nomads-2026.html",
    "cheapest-countries-to-retire-abroad-2026.html",
    "digital-nomad-visas-guide.html",
    "expat-guide-colombia.html",
    "expat-guide-japan.html",
    "expat-guide-malaysia.html",
    "expat-guide-mexico.html",
    "expat-guide-portugal.html",
    "expat-guide-spain.html",
    "expat-guide-thailand.html",
    "expat-guide-uae.html",
    "expat-guide-vietnam.html",
    "expat-guides.html",
    "retirement-visa-guide.html",
    "schengen-visa-guide-2026.html",
]

# New lang dropdown entries
NEW_LANG_DROPDOWN = {
    "zh": '<a class="dropdown-item" href="/{lang}/{file}"><span class="fi fi-cn"></span> 中文</a>',
    "th": '<a class="dropdown-item" href="/{lang}/{file}"><span class="fi fi-th"></span> ไทย</a>',
    "ru": '<a class="dropdown-item" href="/{lang}/{file}"><span class="fi fi-ru"></span> Русский</a>',
    "ar": '<a class="dropdown-item" href="/{lang}/{file}"><span class="fi fi-sa"></span> العربية</a>',
    "ja": '<a class="dropdown-item" href="/{lang}/{file}"><span class="fi fi-jp"></span> 日本語</a>',
    "ko": '<a class="dropdown-item" href="/{lang}/{file}"><span class="fi fi-kr"></span> 한국어</a>',
}

updated = 0

for filename in GUIDE_FILES:
    for lang in ["en","fr","es","pt"]:
        fpath = os.path.join(WWW, lang, filename)
        if not os.path.exists(fpath):
            continue

        html = open(fpath, encoding="utf-8").read()
        changed = False

        # 1. Update hreflang — add zh/th/ru/ar/ja/ko entries
        # Check if zh hreflang already exists
        if 'hreflang="zh"' not in html:
            new_hreflang = "\n".join([
                f'    <link rel="alternate" hreflang="zh" href="{BASE}/zh/{filename}"/>',
                f'    <link rel="alternate" hreflang="th" href="{BASE}/th/{filename}"/>',
                f'    <link rel="alternate" hreflang="ru" href="{BASE}/ru/{filename}"/>',
                f'    <link rel="alternate" hreflang="ar" href="{BASE}/ar/{filename}"/>',
                f'    <link rel="alternate" hreflang="ja" href="{BASE}/ja/{filename}"/>',
                f'    <link rel="alternate" hreflang="ko" href="{BASE}/ko/{filename}"/>',
            ])
            # Insert before x-default
            html = html.replace(
                f'    <link rel="alternate" hreflang="x-default"',
                new_hreflang + '\n    <link rel="alternate" hreflang="x-default"'
            )
            changed = True

        # 2. Fix lang dropdown — replace /zh/destination.html etc. with /zh/{filename}
        for nl in NEW_LANGS:
            flag_map = {"zh":"fi-cn","th":"fi-th","ru":"fi-ru","ar":"fi-sa","ja":"fi-jp","ko":"fi-kr"}
            label_map = {"zh":"中文","th":"ไทย","ru":"Русский","ar":"العربية","ja":"日本語","ko":"한국어"}
            flag = flag_map[nl]
            label = label_map[nl]

            old_pattern = rf'href="/{nl}/[^"]*"(><span class="fi {flag}"></span> {re.escape(label)}</a>)'
            new_href = f'href="/{nl}/{filename}"'
            result = re.sub(old_pattern, new_href + r'\1', html)
            if result != html:
                html = result
                changed = True

        if changed:
            with open(fpath, "w", encoding="utf-8") as f:
                f.write(html)
            updated += 1

print(f"Updated {updated} EN/FR/ES/PT guide pages")

# Also fix zh/th/ru/ar/ja/ko guide pages — fix dropdown links to other new langs
for filename in GUIDE_FILES:
    for lang in NEW_LANGS:
        fpath = os.path.join(WWW, lang, filename)
        if not os.path.exists(fpath):
            continue

        html = open(fpath, encoding="utf-8").read()
        changed = False

        # Fix dropdown links for other new langs pointing to /destination.html
        for nl in NEW_LANGS:
            flag_map = {"zh":"fi-cn","th":"fi-th","ru":"fi-ru","ar":"fi-sa","ja":"fi-jp","ko":"fi-kr"}
            label_map = {"zh":"中文","th":"ไทย","ru":"Русский","ar":"العربية","ja":"日本語","ko":"한국어"}
            flag = flag_map[nl]
            label = label_map[nl]

            old_pattern = rf'href="/{nl}/[^"]*"(><span class="fi {flag}"></span> {re.escape(label)}</a>)'
            new_href = f'href="/{nl}/{filename}"'
            result = re.sub(old_pattern, new_href + r'\1', html)
            if result != html:
                html = result
                changed = True

        if changed:
            with open(fpath, "w", encoding="utf-8") as f:
                f.write(html)
            updated += 1

print(f"Total updated: {updated} guide pages")
print("DONE")
